### ISSUE TITLE
okta-vue getUser() immediately after authentication returns undefined

### ISSUE THREAD

**Issue by hawk4031** [okta/okta-oidc-js#713] opened 2020-03-18 18:00 UTC
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [X] okta-vue

## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

I followed the documentation on the okta-vue page that shows how to integrate the library with PKCE. After the redirect from Okta back to my application happens, I call the `getUser()` method in my App.vue file `created()` method and attempt to use the returned object, but the return object is undefined. This only occurs during the initial authentication process. If I refresh the browser window, everything works as expected as the cookie already exists and is valid. 

## Expected behavior

The call to `getUser()` should be able to return the correct object after redirection happens

## Minimal reproduction of the problem with instructions

I implemented (from what I can tell) the code exactly based on the instructions in the `okta-vue` documentation.

## Environment

- Package Version: 1.1.1
- Browser: Chrome 80.0.3987.132
- OS: Windows 10
- Node version (`node -v`): v12.14.0
- Other: VueJS 2.6.10

**Comment by swiftone** [comment] 2020-03-20 20:43
@hawk4031 - Thanks for the report, sorry you're encountering troubles.  

Can we get a little more detail on your case?  You mention following the instructions - are you using our ImplicitCallback component?

This error usually occurs when the async call to determine if the user is logged in hasn't finished before getUser() is called.

**Comment by hawk4031** [comment] 2020-03-20 20:57
Yes I am using Auth.handleCallback(). It could be the order events are firing but from what I can tell, the getUser() method call is firing after the implicit callback happens. But it could still be a timing problem. Do you have a suggestion on a way I could determine if that’s the case?

**Comment by swiftone** [comment] 2020-04-03 20:54
Internal ref: OKTA-288360

**Comment by hawk4031** [comment] 2020-04-20 13:47
@swiftone Wanted to check on the status of this and to see if I could provide any further information.

**Comment by swiftone** [comment] 2020-05-01 18:57
@hawk4031 - no updates on the SDK at the moment.  You can always reach out to our support team at developers@okta.com and they can help prioritize any issues as well as explore our collection of solutions.

**Comment by brue-chwy** [comment] 2020-06-16 19:30
I am experiencing the same issue. Spent that last day debugging my app with various timing changes to no avail.

**Comment by hawk4031** [comment] 2020-06-16 19:52
I will leave some information here about how I ended up solving this. Essentially, all I did was create my own ImplicitCallback component that does exactly what the one included in the library does but also has my own code in it. 

The `ImplicitCallback.vue` component in `okta-auth-js` looks like:

```javascript
export default {
  name: 'ImplicitCallback',
  async beforeMount () {
    await this.$auth.handleAuthentication()
    this.$router.replace({
      path: this.$auth.getFromUri()
    })
  },
  render () {}
}
```

The first thing I did was copy this into my own component and then add code to place my claims data into a Vuex store. Note the code here is in Typescript, but should be pretty much identical in Javascript.

```typescript
import { Component, Vue } from 'vue-property-decorator';
import AppModule from '@/store/app/index';

@Component
export default class ImplicitCallback extends Vue {
  async beforeMount() {
    await this.$auth.handleAuthentication();

    const claims = await this.$auth.getUser();

    AppModule.updateUserClaims(claims);

    this.$router.replace({
      path: this.$auth.getFromUri(),
    });
  }

  render() {}
}
```

I use this component on my `/implicit/callback` route instead of `Auth.handleCallback()`.

**Comment by brue-chwy** [comment] 2020-06-16 19:54
And of course, right when I reach out for help, I make some headway. I wrapped my `this.$auth.getUser()` call in a `setTimeout` of 2 seconds and now the result of getUser() works as you'd expect. This implies requests are not being handled correctly inside getUser().

**Comment by aarongranick-okta** [comment] 2021-04-14 00:03
@hawk4031 @brue-chwy We have made several updates to `@okta/okta-auth-js` and `@okta/okta-vue` which should have resolved this issue. I am closing this as a duplicate of https://github.com/okta/okta-vue/issues/15

If you are still having problems with `@okta/okta-vue` please create a new issue here: https://github.com/okta/okta-vue/issues

**Closed by aarongranick-okta** 2021-04-14 00:03 UTC
