### ISSUE TITLE
Token expiration results in a 400 error, PKCE verification failed

### ISSUE THREAD

**Issue by polklabs** [okta/okta-oidc-js#839] opened 2020-07-17 20:33 UTC
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Logging in after the token expiration and Okta session expiration results in a 400 error on the token endpoint

The endpoint /oauth2/v1/token returns ```{"error":"invalid_grant","error_description":"PKCE verification failed."}```

The angular okta sign in widget properly logs in to okta and the authn, authorize and callback properly connect. It only fails once it gets to the token

Going back to the login and trying again works fine, it's only on the first login after token expriation

## Expected behavior

Okta should not return an error from the token endpoint when i've already logged into Okta.

## Minimal reproduction of the problem with instructions

Only really able to test the error once a day since it requires the token and okta session to expire

## Environment

- Package Version: 2.1.0
- Browser: Chrome
- OS: Windows 10
- Node version (`node -v`): v10.15.3
- Other: @okta/okta-signin-widget@4.2.1

**Comment by sleepwalky** [comment] 2020-07-20 12:12
https://github.com/okta/okta-oidc-js/issues/804

**Comment by aarongranick-okta** [comment] 2020-07-31 15:32
Duplicate of https://github.com/okta/okta-oidc-js/issues/804

**Closed by aarongranick-okta** 2020-07-31 15:32 UTC
