### ISSUE TITLE
OktaAuthService.getUser() throws TypeError

### ISSUE THREAD

**Issue by jakehockey10** [okta/okta-oidc-js#192] opened 2018-04-17 16:33 UTC
Hello,

I'm using the latest version of the `@okta/okta-angular` npm package and the interface has changed quite a bit.  Some things are now promises while other things are not.  And I used to be able to access the `TokenManager`.  Not sure if that is possible now.

But when I use `getUser` from the service, I sometimes get this error:

```
TypeError: Unable to get property 'sub' of undefined or null reference
```

I'm having a little bit of trouble with the new interface because I attempted to wrap the `OktaAuthService` with my own `AuthenticationService` so that I could cache things and have a central location for authentication related questions and activities.  Now that things are promise-based (like the access token and user claims object), my app can't initialize in the same way that I have had it initialize before.  Not a huge difference, but I wanted to generally asks if I'm approaching this right.  Should I be trying to cache the results of `getUser`, `isAuthenticated`, `getAccessToken`, etc. or should I be using these methods any time a component or service needs to know the value of them?  Does the `@okta/okta-angular` library handle excessive calls to remote authorization servers for me?

**Comment by jmelberg-okta** [comment] 2018-04-17 21:53
Hey @jakehockey10!

First, let me recommend what you should/shouldn't cache:
1. `getUser`: Absolutely. It is very common to take the response from this method and create/query for a user. If at any time the user's claims update, you can call this method again.
2. `isAuthenticated`: I'd suggest **not** caching this response. This provides local validation that the `accessToken` and `idToken` have not expired. If you cache this response, you may be referencing an expired user.
3. `getAccessToken`: By default, an `accessToken` will get refreshed if it has expired. Similar to the `isAuthenticated` method, I'd recommend **not** caching this value to ensure your app is aware of the current state of the user.

> Does the `@okta/okta-angular` library handle excessive calls to remote authorization servers for me?

It doesn't, but I like the suggestion! We have an [open enhancement](https://github.com/okta/okta-oidc-js/issues/35) to add support for an HTTP interceptor, during which we'd explore adding retry logic, a backoff strategy, etc. Want to create an issue for the enhancements you'd like to see?

Regarding the error mentioned in your comment - are you waiting for waiting for the response to resolve? Here is an example of how we are waiting for `getUser` to finish, and populate the UI with the claims: [`samples-js-angular/otka-hosted-login`](https://github.com/okta/samples-js-angular/blob/master/okta-hosted-login/src/app/profile/profile.component.ts#L34-L37).

Hope this helps!

**Comment by jakehockey10** [comment] 2018-04-19 16:33
@jmelberg-okta Thank you so much for the suggestions!  I took your suggestions into account and things are working much better for me, thank you!

**Comment by jakehockey10** [comment] 2018-04-19 16:35
In terms of enhancements, I'll think of a better way to phrase it and try to write something up!  Thanks!

**Comment by jakehockey10** [comment] 2018-04-19 17:01
As for the error, I'm still seeing it locally and in a deployed dev environment.  I think it is IE 11 related though.  I don't remember seeing the issue in other browsers.  But yes, any time I call `getUser`, I'm using `await`.

**Comment by jakehockey10** [comment] 2018-04-19 20:47
@jmelberg-okta Some more info on the error: I am indeed using `await` on each usage of `getUser` but I found out that i was actually doing this twice when I only needed to do it once.  It seems to be a timing issue on IE only, but it also only occurs on the second call the `getUser`.  I don't know if this narrows it down at all?

**Comment by jakehockey10** [comment] 2018-04-20 19:59
@jmelberg-okta Could I talk to you a little bit more about this?  I'm still having issues with `getUser`:
```
TypeError: Unable to get property 'sub' of undefined or null reference
```
It happens way more frequently in IE11.  After authenticating through the redirect flow, and as my application is bootstrapping again, the `app.component.ts`'s `ngOnInit()` method is being called before the `OktaAuthService`'s authentication state is emitted.  So I wait for the authentication state is emitted before setting up the contents of my main menu, which depends on whether you are authenticated or not as well as whether or not I can get the user.  Any time I need to `await` the `getUser` method, I `await` the `isAuthenticated` first, and if `isAuthenticated`, then I await the promise of `UserClaims`.  But this call is what ends up throwing the error.

The error seems to be thrown after calling into `okta-auth-js`'s `getUserInfo` method in the `token.js` file.  This method is returning undefined, and hence the error.  But looking at that source code seems to only return undefined if the access token isn't right or missing.  But before going into `okta-auth-js`, it seems that the access token IS there.

Any ideas on how I can diagnose this and avoid it in the future?

**Comment by jmelberg-okta** [comment] 2018-04-20 20:25
Hey @jakehockey10,

My guess is this could be due to a couple of issues. Since this *only* occurs in IE 11, can you verify that **Third-party cookies are enabled**? You can see how to via [visit this forum post](https://devforum.okta.com/t/cant-get-session-with-the-widget-or-js-auth-sdk-on-ie11/135/2).

After a user's `accessToken` is expired, it'll attempt to refresh it by leveraging the Okta session. Without third-party cookies allowed, this request will fail and the `accessToken` will become `undefiend`.

The second reason could be that `isAuthenticated` is returning `true` because you have a valid `idToken`, not `accessToken`. Are your requesting both? For example, your configuration should look similar to:

```ts
const oktaConfig = {
  issuer: 'https://{yourOktaDomain}.com/oauth2/default',
  clientId: '{clientId}',
  redirectUri: 'http://localhost:{port}/implicit/callback',
  responseType: 'id_token token'
}
```

Let me know if this solves the issue!

**Comment by jakehockey10** [comment] 2018-04-20 21:42
Here is my IE 11 settings.  I had to add my issuer to the sites collection of trusted sites as well.  The only thing I hadn't done was specify the responseType in my oktaConfig.  I hadn't had to do this before, while still getting an access token.  

![image](https://user-images.githubusercontent.com/1821383/39074179-aa85d46a-44ad-11e8-8628-860ed945d497.png)
![image](https://user-images.githubusercontent.com/1821383/39074217-c58a4ffc-44ad-11e8-9373-ba72888a6828.png)

It's really hard to tell what the problem is because I'm also having live-reload issues with IE.  Developing for IE is pretty freaking painful!  I have to restart the browser a lot anyway.

The issue seems to have calmed down a little bit, but I'm still seeing the issue occasionally.  It has to be something I'm doing timing-wise...

**Comment by jmelberg-okta** [comment] 2018-04-20 22:05
You're most likely running into [the race condition](https://github.com/okta/okta-auth-js/issues/92#issuecomment-374820247) described in `okta-auth-js`. Since this library uses it under the hood, that issue is propagated up into the integrations.

You can validate this by waiting for your `accessToken` to expire (~1 hour) and refreshing the page. The `isAuthenticated` method will return `true`, but the token you're using to hit the `/userinfo` endpoint via `getUser()` is invalid - hence the error.

Our team is working on getting this fixed as soon as possible, so I apologize for the inconvenience this is creating.

**Comment by jakehockey10** [comment] 2018-04-21 08:04
Ah that sounds like it could be it. Thanks for helping me curb the feeling of insanity!

**Comment by jakehockey10** [comment] 2018-04-24 19:15
@jmelberg-okta , I'm pulling in `okta-auth-js` and trying to use the TokenManager to listen to the `refresh` event and try to `getUser` again.  Is this how you would get around this issue until the fix comes in?  It doesn't seem to fire the event on app load, but I get subsequent refresh firings...

**Comment by RaduGrama** [comment] 2018-06-19 15:17
@jmelberg-okta, prior to calling `await this.oktaAuth.getUser()`, does a call to `await this.oktaAuth.getAccessToken()` or `await this.oktaAuth.getIdToken()` help? Does any of those two calls ensure the expired token is refreshed, or do they suffer from the same race condition issue?

**Comment by jmelberg-okta** [comment] 2018-09-25 02:58
This issue was related to a bug that has since been fixed with [`okta-auth-js@2.x`](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-2.0.1).

All of our integration libraries have been updated to pull in this bug-fix, so please update you app accordingly.

If the issue persists, please feel free to reopen this issue.

**Closed by jmelberg-okta** 2018-09-25 02:58 UTC

**Comment by ShoaibShaukatSystems** [comment] 2019-02-07 11:23
Issue still persist for edge browser? Please share if someone have solution for this?

**Comment by swiftone** [comment] 2019-02-07 16:44
@ShoaibShaukatSystems 
Are you saying the issue is still occurring for Edge even though you are running the latest version of okta-auth-js or relevant SDK?

If so, can you share which SDKs and confirm the experience you see?

**Comment by ShoaibShaukatSystems** [comment] 2019-02-07 19:14
@swiftone 
 We are using @okta/okta-angular 1.0.7. 
For IE 11 and Chrome  it is working fine. For edge Browser I'm still having issues with getUser:
TypeError: Unable to get property 'sub' of undefined or null reference

**Comment by constantinblanariu** [comment] 2020-03-09 12:11
I'm still having this issue, on Chrome. But maybe it's something I'm doing wrong.
I'm using @okta/okta-angular@1.4.0

After about 1h if I refresh the page I'm getting

`TypeError: Cannot read property 'name' of undefined`

The code is below:

``` typescript
async ngOnInit() {
    this.isAuthenticated = await this.oktaAuth.isAuthenticated();
    if (this.isAuthenticated) {
      const oktaGetUser = this.oktaAuth.getUser().then(
        (userClaims) => this.displayName = userClaims.name
      )
    }
}
 ```
