### ISSUE TITLE
[BUG?] @okta/okta-vue login bug

### ISSUE THREAD

**Issue by metasean** [okta/okta-oidc-js#439] opened 2019-05-03 21:14 UTC
## I'm submitting this issue for the package(s): 

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [x] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

I’m trying to set-up Okta in a new Nuxt js application.

I’ve got it most of the way there, but on redirect to `http://localhost:8081/implicit/callback` it goes there and then _immediately redirects_ to **`http://localhost:8081/implicit/[object%20MouseEvent]`** (even if I never touch a mouse device during the process).

## Expected behavior
Redirect only to `http://localhost:8081/implicit/callback` or an address that I've already supplied to `router.js`

## Minimal reproduction of the problem with instructions
1. Clone:  https://github.com/metasean/okta-troubleshooting/tree/add-okta-nuxt-spa
  _NOTE:_ important code is on the `add-okta-nuxt-spa` branch
2. `npm install`
3. `npm run develop`

## Extra information about the use case/user story you are trying to implement
Once you've seen the problem, then replace `node_modules/@okta/okta-vue/src/components/implicitCallback.vue` with the following and re-run it.

```javascript
<script>
export default {
  name: 'ImplicitCallback',
  async beforeMount () {
    await this.$auth.handleAuthentication()
    // const path = await this.$auth.getFromUri()
    // DOES NO GOOD
    // console.log('path:', path)

    // THIS IN CONJUNCTION WITH THE SAME CALL INSIDE
    // this.$router.replace
    // IS THE ONLY THING THAT SEEMS TO MAKE IT WORK
    this.$auth.getFromUri()                    // FIRST CALL
    
    this.$router.replace({
      path: this.$auth.getFromUri()           // SECOND CALL
    })
  },
  render () {}
}
</script>
```

## Environment

- Package Version: 1.1.0
- Browser: Chrome Canary  76.0.3782.0
- OS: macOS Mojave 10.14.4 (18E226)
- Node version (`node -v`): v10.15.3

Also posted over at https://devforum.okta.com/t/odd-login-problem/5023

**Comment by swiftone** [comment] 2019-05-08 21:29
Thank you for the detailed report - This will really help diagnose what is going on.  Based on the forums you appear to have a work-around in place.  Please let us know if that is not the case.

**Comment by metasean** [comment] 2019-05-09 16:22
@swiftone - I was able to work-around it, but I promptly ran into a second okta-vue-related hiccup.  Thankfully, I was able to find a work around for that also.  

On the other hand, I had used the @nuxtjs/router module and was hard-coding routes during the process of connecting Okta. Unfortunately I can't use @nuxtjs/router in conjunction with the "pages" directory of a Nuxt SPA app <img src="https://emoji.slack-edge.com/T0C4J5J3W/eye-twitch/6c322673eabf611d.gif" width="15px">.  

So, at this point, I'm still trying to build-out a solid Nuxt-SPA/Okta integrated example.  
Once I do, I'll post it, along with any of the work-arounds that are still in its codebase.

**Comment by pete-intranel** [comment] 2019-07-11 20:03
In `layouts/default.vue` you have:
`<button v-else id="login-button" @click="$auth.loginRedirect">`

Try replacing with:
`<button v-else id="login-button" @click="$auth.loginRedirect()">`

My guess is that without the parenthesis, the button click event is being passed in as the first parameter, mapping to `fromUri`.

**Comment by swiftone** [comment] 2019-08-13 20:19
@metasean - It looks like the issue is what @pete-intranel identified (Thanks Pete!) with no change required from Okta.  

I'm closing this issue, but if you find additional evidence that I'm closing it in error, please feel free to reopen it or to create a new related issue.

**Closed by swiftone** 2019-08-13 20:19 UTC
Labels: bug, priority-high, requires-reproduce, workaround-available
