### ISSUE TITLE
okta-react: Add function refreshTokens to Auth.js to obtaining new tokens without redirect

### ISSUE THREAD

**Issue by mschaeffner** [okta/okta-oidc-js#180] opened 2018-04-09 10:05 UTC
Add a new function to [Auth.js](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/src/Auth.js) so that one can obtain new tokens in the background of an React application without redirecting the page.

This is similar to [auth.redirect({sessionToken})](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#authredirectsessiontoken). But without a redirect, so that it will result in a much better user experience.

Implementation can be done by using the function [token.getWithoutPrompt(oauthOptions)](https://github.com/okta/okta-auth-js#tokengetwithoutpromptoauthoptions) of the underlying `_oktaAuth` client. 

I'd suggest to call this new function `refreshTokens`, because `get...Token` is already used to access the `id_token` and `access_token` locally from the browser.

**Comment by jmelberg-okta** [comment] 2018-09-25 03:08
Thanks @mschaeffner for the ask. We are tracking this under #227.

Closing this issue as a duplicate of #227

**Closed by jmelberg-okta** 2018-09-25 03:08 UTC
