### ISSUE TITLE
Error: npm install @okta/okta-react-native --save  

### ISSUE THREAD

**Issue by pmcdowell-okta** [okta/okta-oidc-js#822] opened 2020-07-08 20:25 UTC
Weird, got an error on the first step of the **React Native** project

```bash
MacBook-Pro:okta-react-native pm$ npm install @okta/okta-react-native --save
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://artifacts.aue1d.saasure.com/artifactory/api/npm/npm-okta/@okta%2fokta-react-native failed, reason: getaddrinfo ENOTFOUND artifacts.aue1d.saasure.com
```bash

Here is the Debug Log

```bash
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@okta/okta-react-native',
1 verbose cli   '--save'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose npm-session da5f7bc96deff49c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for @okta/okta-react-native@latest request to https://artifacts.aue1d.saasure.com/artifactory/api/npm/npm-okta/@okta%2fokta-react-native failed, reason: getaddrinfo ENOTFOUND artifacts.aue1d.saasure.com
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 66ms
10 verbose type system
11 verbose stack FetchError: request to https://artifacts.aue1d.saasure.com/artifactory/api/npm/npm-okta/@okta%2fokta-react-native failed, reason: getaddrinfo ENOTFOUND artifacts.aue1d.saasure.com
11 verbose stack     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
11 verbose stack     at ClientRequest.emit (events.js:210:5)
11 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:406:9)
11 verbose stack     at TLSSocket.emit (events.js:210:5)
11 verbose stack     at emitErrorNT (internal/streams/destroy.js:92:8)
11 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
12 verbose cwd /private/tmp/okta-oidc-js/packages/okta-react-native
13 verbose Darwin 18.5.0
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@okta/okta-react-native" "--save"
15 verbose node v12.13.0
16 verbose npm  v6.12.0
17 error code ENOTFOUND
18 error errno ENOTFOUND
19 error network request to https://artifacts.aue1d.saasure.com/artifactory/api/npm/npm-okta/@okta%2fokta-react-native failed, reason: getaddrinfo ENOTFOUND artifacts.aue1d.saasure.com
20 error network This is a problem related to network connectivity.
20 error network In most cases you are behind a proxy or have bad network settings.
20 error network
20 error network If you are behind a proxy, please make sure that the
20 error network 'proxy' config is set properly.  See: 'npm help config'
21 verbose exit [ 1, true ]
```bash

**Comment by shuowu** [comment] 2020-07-10 23:15
Close this issue as it's caused by local environment.

**Closed by shuowu** 2020-07-10 23:15 UTC
