### ISSUE TITLE
Cannot find module '@okta/okta-react' AFTER 1.1.2 update

### ISSUE THREAD

**Issue by rodoabad** [okta/okta-oidc-js#331] opened 2018-10-17 15:30 UTC
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Updating to `@okta/okta-react` version `1.1.2` breaks existing module requires.

## Expected behavior

It should not break because as far as semantic versioning is concerned, it is supposed to be a path/fix.

## Minimal reproduction of the problem with instructions

Set `^1.1.1` in your `package.json` and nuke and install. This should install `1.1.2` since `^` covers this.

Require `@okta/okta-react` and run your tests. It should fail.

## Environment

- Package Version: 1.1.2
- Browser: None
- OS: Mac and Windows
- Node version (`node -v`): 10.9.0
- NPM version: 6.4.1

**Comment by rodoabad** [comment] 2018-10-17 15:50
@jmelberg-okta have you guys tested this by requiring the published package? This is currently breaking everyone.

https://github.com/okta/okta-oidc-js/pull/318 https://github.com/okta/okta-oidc-js/pull/328

**Comment by jmelberg-okta** [comment] 2018-10-17 16:08
Thanks for the report @rodoabad - I'm investigating this now. I'll follow up shortly.

**Comment by Steague** [comment] 2018-10-17 17:03
I'm pretty sure this is what is happeneing to me. 

`Module not found: Can't resolve '@okta/okta-react' in '...'
`
- Package Version: 1.1.2
- Browser: Chrome
- OS: Mac
- Node version (node -v): 8.11.2
- NPM version: 6.1.0

**Comment by rodoabad** [comment] 2018-10-17 17:05
@Steague you are exactly correct. If you revert back to `1.1.1` it fixes it.

**Comment by Steague** [comment] 2018-10-17 17:57
@rodoabad Confirmed, reverting to v1.1.1 causes the error to go away.

**Comment by jmelberg-okta** [comment] 2018-10-17 18:11
Thanks again for your patience @rodoabad and @Steague. I've identified that the issue is related to our internal CI failing to trigger `npm prepublish` when `npm publish` was called.

I'm promoting new versions of each of the affected packages and will close this issue once they're made public.

**Comment by rodoabad** [comment] 2018-10-17 18:16
@jmelberg-okta glad to help!

![giphy](https://user-images.githubusercontent.com/1240667/47107377-ccac0200-d20e-11e8-80ad-9e345be1e17a.gif)

**Comment by jmelberg-okta** [comment] 2018-10-17 18:18
The following packages have been updated and are now public:

- `@okta/okta-angular@1.0.6`
- `@okta/okta-react@1.1.3`
- `@okta/okta-vue@1.0.6`

**Closed by jmelberg-okta** 2018-10-17 18:18 UTC
