### ISSUE TITLE
OktaCallbackComponent does not pickup the token with HashLocation

### ISSUE THREAD

**Issue by truginis** [okta/okta-oidc-js#262] opened 2018-08-14 19:29 UTC
Auth does not work when using ```HashLocationStrategy```. Need hashbang for older browser support.

**Comment by jmelberg-okta** [comment] 2018-08-15 05:00
Hi @truginis,

The OAuth 2.0 spec [requires that only one hash fragment exist](https://tools.ietf.org/html/rfc6749#section-3.1.2) on a redirection endpoint.

Please see the conversation in [#29](https://github.com/okta/okta-oidc-js/issues/29#issuecomment-342339960) for more information.

Closing this as a duplicate of #210 and #29.

**Closed by jmelberg-okta** 2018-08-15 05:00 UTC
