### ISSUE TITLE
Angular OktaAuthService.loginRedirect() not working in IE11

### ISSUE THREAD

**Issue by bjaminp** [okta/okta-oidc-js#633] opened 2019-12-16 16:14 UTC
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [X] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
The Okta oktaService.loginRedirect() call does not seem to be doing anything in IE11. It works fine in Chrome/Firefox/Edge.

## Expected behavior
It should redirect to my organization's login page

## Minimal reproduction of the problem with instructions
1. Create a new angular app. (ng new) and configure to work in IE11
2. Add @okta/okta-angular module
3. Import into app module.
4. Provide config:
`
provide: OKTA_CONFIG, useValue: {
        issuer: 'https://xxxx.okta.com',
        redirectUri: 'http://localhost//implicit/callback',
        clientId: '',
        scopes: ['openid', 'profile', 'email'],
        pkce: false
      }
`
5. Inject oktaAuthService in app.component
6. Create a button that call oktaAuthService.loginRedirect('/');
7. ng serve

## Environment

- Package Version: 1.3.0
- Browser: IE11
- OS: Windows 10
- Node version (`node -v`): 12.13.1
- Other: Angular version: 8.2.14

**Comment by swiftone** [comment] 2019-12-16 22:05
@bjaminp - Thanks for the report.  We'll look into this, but this smells like a polyfill for IE11 is missing.  (By and large we don't try to polyfill to much ourselves because we don't want to complicate/conflict with your build process and your own polyfills)

**Comment by swiftone** [comment] 2019-12-16 22:06
Internal Ref: OKTA-267233

**Comment by bjaminp** [comment] 2019-12-18 16:07
I'm wondering if this is related.
https://github.com/okta/okta-auth-js/issues/240

**Comment by aarongranick-okta** [comment] 2019-12-19 00:48
@bjaminp I was able to reproduce this issue using our sample angular app. 

The cause of the error appears to be a use of `Array.includes` in the `@okta/okta-auth-js` library. https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/lib/token.js#L625

This method is not supported on IE 11:
https://caniuse.com/#feat=array-includes

I was able to get the sample app working by using this polyfill: https://www.npmjs.com/package/polyfill-array-includes

We will fix the issue with `@okta/okta-auth-js` in an upcoming release. In the meantime, I recommend using a polyfill to overcome this issue.

**Comment by kjavia** [comment] 2020-02-06 17:03
For me after all the polyfills are added and after a successful sign in, IE11 redirects to the server side page `https://dev-xxxxx.okta.com/signin/verify/okta/sms` instead of the component defined in `implicit/callback` route. Works well in Chrome and Edge. Is there a way to debug the unminized code that is loded with `okta-angular` package? The code is somewhere in this file 

https://github.com/okta/okta-oidc-js/blob/40155af38840f4a66540ddb12589aa0398c50845/packages/okta-angular/src/okta/services/okta.service.ts

however this file is minimized when it's running and hard to debug what's going on.

**Comment by swiftone** [comment] 2020-02-07 21:32
@kjavia - Your description sounds like a separate issue.  Would you mind opening that as a separate GH issue with details?

**Comment by aarongranick-okta** [comment] 2020-02-07 22:43
@kjavia We provide sourcemaps along with our minified bundle. If you are using webpack to build your app, you can process these sourcemaps using `source-map-loader` plugin: https://www.npmjs.com/package/source-map-loader

That being said, I think the issue with the widget and MFA might be unrelated to the okta-angular library. It is more likely related to the signin widget: https://github.com/okta/okta-signin-widget (which also has sourcemaps).

We provide support for both okta-angular and the signin-widget. As I recall, there are certain MFA flows which require a redirect to a server-side page. However, you definitely should not have to enter a code twice.

**Comment by swiftone** [comment] 2020-02-21 21:38
This issue appears to be resolved by https://github.com/okta/okta-oidc-js/issues/633#issuecomment-567278452.  (And the sourcemaps question to another issue)

If someone has an IE11 issue that isn't resolved as described above, please open a new issue with details.

**Closed by swiftone** 2020-02-21 21:38 UTC
