### ISSUE TITLE
login_required, error.description: The client specified not to prompt, but the user is not logged in.

### ISSUE THREAD

**Issue by hydanjan** [okta/okta-oidc-js#460] opened 2019-05-22 17:34 UTC
This is related to #282 

It still happens with all the okta-angular versions i have tried with when a client has an accessToken or idToken in the localStorage but the Okta session is expired/not active on the server. The error logs in the console when the TokenManager tries to get new access token before expiration of the current access token.

Steps to reproduce:
1) Login to the angular application with the sign in widget
2) Open another tab, navigate to your okta org url. Since there is a session, it should login with the active user.
3) Logout from Okta org url, which ends the user session
4) Wait for the TokenManager to trigger /authorize to refresh the access token ( I have my access token timeout set to 5 mins in the auth server)
5) Notice the error in browser console

Is there any work around to take the user back to login screen when that error occurs?
Currently user has to refresh the page to take to the login screen after session expired/closed in other forms.

The fix that's referred in 1.0.4 just checks for the access token and id token in the local storage but this happens when the token manager tries to get a new access token before expiration of the current access token but user session is already expired or killed in other forms like i have listed in #3 above. 

Angular: 4.x
@okta/angular: Tried with multiple versions. 1.0.4 and 1.2.1
@okta/okta-signin-widget: 2.10.0
Browser: Chrome

Please let me know for any additional details. Thanks!!
![image](https://user-images.githubusercontent.com/29308478/58195566-deb2bf00-7c8d-11e9-803c-320a7433f909.png)

**Comment by cloudtagger** [comment] 2019-05-28 02:13
same issue with vue.

**Comment by cpitt** [comment] 2019-05-28 17:34
Also experiencing this

**Comment by cloudtagger** [comment] 2019-08-18 13:35
3 moths later. Just checking in. Any fix for this?

**Comment by swiftone** [comment] 2019-08-21 21:47
We've confirmed the issue - because it only impacts stale/invalid sessions it hasn't reached the top of the priority list yet but it is not being ignored.  People 👍 this issue are not unnoticed.

**Comment by cloudtagger** [comment] 2019-08-22 03:05
Any workaround for this in Vue while it is being fixed. This is happening for me every time the session times out for whatever reason. No user log out necessary. It will not auto renew and I'm not sure where to access this error from to be able to mitigate it with a try/catch or at least warn the user.
thanks

**Comment by swiftone** [comment] 2019-08-28 21:40
@cloudtagger - We've created a task to fix this.  In the meantime, I have only vague suggestions  - if you clear the local storage the application should redirect to the login page correctly.  As for trapping the error, the Vue SDK doesn't have a method to provide your own AuthJS instance like React/Angular SDKs (we've added a task to fix that too) so catching the error will be a bit more involved, I'm afraid.

Sorry I don't have an immediate answer, but feel free to provide more information or contact developers@okta.com to contact our support staff in the meantime.

**Comment by cloudtagger** [comment] 2019-08-29 12:08
Thanks for trying to help. Although I can't clear the local storage if I can't catch the error to know when to do so.

**Comment by riteshmaurya** [comment] 2019-09-23 20:18
I am also facing same issue when client is not active for long. 

error.errorCode: login_required, error.description: The client specified not to prompt, but the user is not logged in.
onWindowLoadHandler @ thewarehousegroup.okta.com/oauth2/v1/authorize?client_id=******************&nonce=**************************&prompt=none&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fff-ui%2Fauthorization-code%2Fcallback&response_mode=okta_post_message&response_type=id_token&state=********************************&scope=openid:42

**Comment by petemcwilliams** [comment] 2019-09-24 07:47
For me I am getting the issue on trying to refresh the token in a new safari window when the tokens are still active.

```
[Error] ERROR
Error: Uncaught (in promise): OAuthErrorEvent: {"type":"silent_refresh_error","reason":{"state":"490MxGDbFdPida089-SidwIAoXr3ADMbzM3fO_UwwBB2w","error":"login_required","error_description":"The+client+specified+not+to+prompt,+but+the+user+is+not+logged+in."},"params":null}
resolvePromise — zone-evergreen.js:797
(anonymous function) — zone-evergreen.js:707
rejected — okta-auth-manger.js:16:88
onInvoke — core.js:39698
run — zone-evergreen.js:124
(anonymous function) — zone-evergreen.js:855
onInvokeTask — core.js:39679
runTask — zone-evergreen.js:168
drainMicroTaskQueue — zone-evergreen.js:559
invokeTask — zone-evergreen.js:469
invokeTask — zone-evergreen.js:1603
globalZoneAwareCallback — zone-evergreen.js:1629
	defaultErrorLogger (vendor.js:52944)
	handleError (vendor.js:52996)
	next (vendor.js:83567)
	(anonymous function) (vendor.js:79143)
	__tryOrUnsub (vendor.js:153469)
	next (vendor.js:153408)
	_next (vendor.js:153358)
	next (vendor.js:153335)
	next (vendor.js:153121)
	emit (vendor.js:79105)
	run (polyfills.js:3130)
	onHandleError (vendor.js:82851)
	runGuarded (polyfills.js:3143)
	microtaskDrainDone (polyfills.js:3669)
	drainMicroTaskQueue (polyfills.js:3572)
	invokeTask (polyfills.js:3475)
	invokeTask (polyfills.js:4609)
	globalZoneAwareCallback (polyfills.js:4635)
```

I'm using angular-oauth2-oidc v8.0.4 to connect to okta.

```
    async login(): Promise<void> {
        await this._oAuthService.loadDiscoveryDocument();

        await this._oAuthService.tryLoginImplicitFlow();
        if (this._oAuthService.hasValidIdToken() && this._oAuthService.hasValidAccessToken()) {
            // we have some valid token at the moment, ask server to refresh
            await this._oAuthService.silentRefresh();

            this._postAuthProcessing();
        } else {
            // we do not have valid tokens contact Okta using the implicit flow, this will return back to the OktaAuthManagerCallbackComponent component.
            this._oAuthService.initImplicitFlow();
        }
    }
```

**Comment by aarongranick-okta** [comment] 2019-09-25 02:20
@cloudtagger We identified and fix several issues related to token renewal in the underlying library `@okta/okta-auth-js`. If you install the latest version of this module in your project alongside `okta-vue` your app should use the newer version without any need to update `okta-vue`. Please let us know if this update fixes the issue for you.

**Comment by swiftone** [comment] 2019-10-14 20:36
Closing as this should be fixed in recent versions.  There is a similar but distinct issue with clients that logout via a separate process that is not covered by this issue.

**Closed by swiftone** 2019-10-14 20:36 UTC
Labels: awaiting-response, bug

**Comment by thethirdheat** [comment] 2020-01-02 20:13
Hi,
I am having this same issue. However I have the latest version of okta-auth-js at version 2.11.0 . To produce the issue I go on private window for safari then log in. First I login with the Okta then I get stuck in a redirection loop going from okta back to my site. I've tried changing how the token is stored from "cookie", to "sessionStorage", to "memory", to "localStorage". The data does not seem to get passed through the redirect back to my site.

This redirect loop is also happening for other users but it seems to only be an issue with safari. Also possibly on mobile?

**Comment by aarongranick-okta** [comment] 2020-01-02 20:25
Hi @thethirdheat,

I'm sorry that you are having issues. This error message can mean several things, hopefully we can resolve it quickly for you. 

Would you mind opening a new issue? Please let us know:

- Which OIDC library you are using, if any (angular, react), if you are using okta-auth-js without an OIDC sdk wrapper, please file the issue here: https://github.com/okta/okta-auth-js
- What is the `loginRedirectUri` for your app? (By default it is `/implicit/callback`).
- Please provide details on your client-side router. Are you using a default Angular/React router? Are you using push state or html fragments for your routes? Is the login callback being handled by a dedicated route?

Generally login callback hits a dedicated route which will read token information from the URL, save it using the `TokenManager` and then redirect back to the original page or the home page of your app. Are you able to place a `debugger` statement on this route and verify that token information is being passed back in the HTML fragment from the Okta login page?

**Comment by jgodha** [comment] 2020-06-11 19:38
Continue to see this error in the latest version of @okta/okta-angular (2.0.0) which uses version 3.0.0 of @okta/okta-auth-js. We have our own callback component which calls OktahAuthService.handleAuthentication and does some other custom stuff. What is the resolution of this issue? Any help is appreciated.

**Comment by MarkWilliams3141** [comment] 2020-06-16 10:54
We also have this issue with @okta/okta-vue. 2.0.0. using @okta/okta-auth-js 3.1.1.

**Comment by corysimmons** [comment] 2020-06-16 17:39
I get this `The client specified not to prompt, but the user is not logged in.` as well. It seems like an invalid token/cookie thing. If you flush your browser of those, it should work, but it would be nice if this library actually did a test for that and just automatically flushed those from localStorage and cookies if the cookies/tokens were invalid.

Doing that would let us just write our apps so "if invalid auth, redirect to login", whereas now we have to do extra checks for it.

**Comment by jasonrberk** [comment] 2020-06-29 20:18
this is still an issue

**Comment by kuehlein** [comment] 2020-07-01 13:44
this is an issue for me as well. I'm using @okta/okta-react v3.0.2 with @okta/okta-auth-js v3.1.4

**Comment by gtupak** [comment] 2020-07-06 14:55
I am also experiencing the same issue with the same packages as @kuehlein

**Comment by shuowu** [comment] 2020-07-10 20:05
A workaround can be listening on the `error` event from auth-js `TokenManager` (https://github.com/okta/okta-auth-js#tokenmanageronevent-callback-context). When `error` happens, redirect to the login page.

Currently, the downstream SDKs are not catching the session error and make default redirect properly, our team is working on a fix now.

**Comment by DarrenAllen** [comment] 2020-07-20 17:10
@shuowu is there an issue tracking that?

**Comment by nayanbhana** [comment] 2020-07-23 06:00
> A workaround can be listening on the `error` event from auth-js `TokenManager` (https://github.com/okta/okta-auth-js#tokenmanageronevent-callback-context). When `error` happens, redirect to the login page.
> 
> Currently, the downstream SDKs are not catching the session error and make default redirect properly, our team is working on a fix now.

@shuowu Is your team aware that this happens on tokenManager.renew(key) as well?

**Comment by shuowu** [comment] 2020-07-23 20:08
@nayanbhana Yes, the renew method actually is the one that emits the `error` event.

**Comment by nayanbhana** [comment] 2020-07-23 23:07
For some reason, my token will actually successfully renew after that error emits. Quite strange behaviour.

**Comment by shuowu** [comment] 2020-07-23 23:49
@nayanbhana Might be caused by concurrency issue, one renew process failed but another one succeed, which ends up with a valid token in storage. The latest version of `okta-auth-js` should be able to handle the concurrency issue. Also, please make sure only one authJs instance is created in your app, since different instances may trigger multiple renew processes with auto-renew turned on.

**Comment by nayanbhana** [comment] 2020-07-28 03:44
@shuowu The problem is I'm using @okta/okta-signin-widget and @okta/okta-vue so I can't really choose which version of okta-auth-js it picks up, right?

**Comment by sajeshMUFC** [comment] 2020-08-17 11:00
I m also facing the same issue in our SPA app
Env :
 "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.8",
    "@fortawesome/free-solid-svg-icons": "^5.5.0",
    "@fortawesome/vue-fontawesome": "^0.1.2",
    "@okta/okta-auth-js": "^3.1.3",
    "axios": "^0.19.0",
    "bulma": "^0.8.2",
    "protobufjs": "^6.9.0",
    "vue": "^2.6.10",
    "vue-router": "^3.0.1",
    "vue-search-select": "^2.9.3"
  }



While trying to open the application after a day , it makes an call to endpoint 
/authorize ,for refresh tokens
<img width="863" alt="Issue_okta" src="https://user-images.githubusercontent.com/6329567/90388933-47ae0000-e0a6-11ea-9211-7e8d97303149.png">

 Since the "prompt" parameter is none ,it does not load okta login page . Is there any error handler while getting id token (Since it is expired )/ how the refresh of token to be handled?
`oktaAuth.tokenManager.get('id_token')
`
Below the Error Summary:

<img width="1065" alt="error-summary" src="https://user-images.githubusercontent.com/6329567/90388890-3664f380-e0a6-11ea-9d12-949fd1385e3e.png">

**Comment by nsingh2018** [comment] 2020-08-17 13:13
I am also getting this error in reactJs:

error.errorCode: login_required, error.description: The client specified not to prompt, but the user is not logged in.

Can someone provide a solution as our production is impeded due to this issue.

**Comment by aarongranick-okta** [comment] 2020-08-18 00:36
@nsingh2018 This console message is normal and expected when attempting to renew a token and the user's session is expired or has been ended. When a token renew fails, the token will be removed from storage. By default, a login flow will be shown when navigating to a secure route if both the ID token and the access token are missing from storage. You may be experiencing unexpected results because only one token is missing. We are going to change this behavior in an upcoming release so a login flow will be shown if either token is missing. In the meantime, if you would like to show a login flow when any token is missing, provide an implementation of `isAuthenticated` as described here: https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#configuration-options

**Comment by chrismllr** [comment] 2020-08-31 14:02
@aarongranick-okta Seeing this problem, but considering that it may be how our okta application or auth server is configured. I am getting this error 1 day after login pretty consistently, when going back to the application after not using overnight. 

Could this be a configuration within our auth server, to auto-expire user sessions 24hr after they are obtained? We also use Okta for logins to things like Gitlab, where I don't see the 24hr user session expiration.

Thanks for any help.

**Comment by shuowu** [comment] 2020-08-31 15:23
@chrismllr As Aaron described here: https://github.com/okta/okta-oidc-js/issues/460#issuecomment-675183021 , it's an error for renew token failed when session is expired.
I am not sure which OKTA SDK your app is using, the expected behavior for the latest client SDKs is to redirect the user to the login page. If you are redirected to the login page with seeing this error, you can just ignore it, as re-login will give you a brand new session.

**Comment by chrismllr** [comment] 2020-09-01 14:02
@shuowu Thanks for the explanation, so the expired session is the root cause. Where is that session length usually defined?

**Comment by shuowu** [comment] 2020-09-01 14:09
@chrismllr You can manage your application's session expiration time in the OKTA admin console by following `Applications -> {your applicaiton} -> Sign On -> Sign On Policy -> Add Rule -> Actions -> Prompt for re-authentication`

**Comment by chrismllr** [comment] 2020-09-01 14:10
@shuowu Thank you very much, will try that now

**Comment by nsingh2018** [comment] 2020-09-01 14:13
I test with a valid login credentials using latest chrome. Okta sign in widget just spins there and does nothing. I tried in chrome incognito window same results. I am using widget version 3.9

**Comment by chrismllr** [comment] 2020-09-01 14:42
@shuowu Those settings look to give us what we need. Is there a reason behind adding another TTL layer on top of the auth server policy? We are trying to educate ourselves on best practice with this setting.

Also for later reference, the inputs for length of time before re-prompt don't appear until you check the "Prompt for reauthentication" box in the UI.

**Comment by shuowu** [comment] 2020-09-01 15:39
@nsingh2018 Have you seen any message from chrome dev console?

**Comment by shuowu** [comment] 2020-09-01 15:48
@chrismllr Auth server is an engine for minting tokens, the application manages the TTL of the app (when can the app get tokens from the auth server). Multiple applications can use the same auth server to mint the tokens. So it makes sense to manage them separately.
Here is an article about okta auth server: https://developer.okta.com/docs/concepts/auth-servers/

**Comment by nsingh2018** [comment] 2020-09-01 15:51
> @nsingh2018 Have you seen any message from chrome dev console?

https://user-images.githubusercontent.com/6329567/90389397-20a3fe00-e0a7-11ea-8a8f-aef01eae3ba9.png

**Comment by shuowu** [comment] 2020-09-01 20:25
@nsingh2018 I am not able to reproduce it locally with @okta/okta-signin-widget@3.9

If you can reach out to our support team at developers@okta.com you can share details of your configuration and they can help us find out what is happening.

**Comment by chrismllr** [comment] 2020-09-02 20:40
@shuowu We were able to successfully add Sign In Rules thanks to your pointers above -- but we are still seeing the issue after logging in and using the application for around 2ish hours. I was able to see two successful token renewals, and then saw this error.

I know the default TTL for an Okta Token is 2h, but we also have an unlimited refresh token. Could there be something else like this at play?

**Comment by shuowu** [comment] 2020-09-02 21:00
@chrismllr In the current version of `auth-js`, the token renew process is via start a login redirect in hidden iframe then message the new tokens to the SDK (not refresh token). Also, it's fine to see the error in the console, as it just means the renewal process failed because of the expired session. Then, it's about how you want to handle the app when the okta session is expired.

The default behavior provides from downstream SDKs (react, angular, vue) is to start a new login flow when both tokens are expired (failed to be renewed).

Also, please make sure you are on auth-js version later than 3.2.3, patches have been added to fix some auto renew related issues.

**Comment by restfulhead** [comment] 2020-09-21 17:55
> The default behavior provides from downstream SDKs (react, angular, vue) is to start a new login flow when both tokens are expired (failed to be renewed).

This is not the case for `"@okta/okta-angular": "~2.2.0"` using `"@okta/okta-auth-js": "^3.2.3"`, or at least it's not working for us. After seeing the error in the log, there is no redirect to the login page (leaving our app broken after the session times out).  Maybe that's because `onSessionExpired` was recently removed (see [Changelog](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-angular/CHANGELOG.md)). I am now trying to implement `getTokenManager().on('error', ...` to redirect manually.

Also we are unable to use `Applications -> {your applicaiton} -> Sign On -> Sign On Policy -> Add Rule -> Actions -> Prompt for re-authentication`. We have Identity Discovery configured and enabling this option breaks the login flow (user is prompted twice for password).

Essentially this means our users will have to log in every 2 hours even though they might be active. This isn't great.

**Comment by chrismllr** [comment] 2020-09-21 18:18
@shuowu We are using v4.0 of the SDK. FWIW, the auth-js library appears to be working as expected. Our frustration, similar to @restfulhead 's, is the 2 hour session expiration.

It could be better illustrated in the documentation, but when new accessTokens are minted, a Session Token/ Cookie (internal to auth-js) is also minted, which by default, expires after 2h of inactivity.

The big disconnect for me was that the explanation of how the auth-js lib handles session expiry (session tokens, cookies, where to configure) was incredibly hard to suss out, and is largely undocumented. Helpful documentation via a Wiki or links to Okta docs would be helpful.

Here is ultimately the configuration we found which allows you to extend the default 2h sign on policy session expiration:
https://help.okta.com/en/prod/Content/Topics/Security/healthinsight/session-lifetime.htm

Although be warned, this is a GLOBAL Okta Organization setting, and cannot be overridden on an application, or authorization server level. It can be assigned Groups when created, but then all members of those groups are beholden to that session timeout, regardless of which application/ auth server they are talking to. **This could be a great feature addition**.

Okta Support suggested we create an entirely separate Okta Organization, and federate with the org we are currently using, which seemed quite heavy handed.

This is where we ultimately hit a dead end, and are living with the Session Expiry of 2 hours until we are able to move logic server-side, or, we move to a separate organization and federate.

**Comment by shuowu** [comment] 2020-09-21 21:15
@restfulhead 
Currently `okta-angular` and `okta-vue` are doing [passive flow on token auto renew](https://github.com/okta/okta-oidc-js/issues/744#issuecomment-668247988).
The `AuthState` evaluation flow will be changed to `active` renew in the next major release, which means authJs will maintain a copy of up to date `AuthState`  in memory and update it when tokens are about to expire, then sync it with the downstream SDKs.

For your issue, please check if `onAuthRequired` callback has been provided, it will replace the default loginRedirect behavior when `isAuthenticated` evaluates to false for `OktaAuthGuard`.

**Comment by restfulhead** [comment] 2020-09-22 13:15
@shuowu Thank you for the information. Will the `active` renew also renew the Okta session then? Or is there any other way to extend the 2 hours (without changing the global Okta setting or creating a separate org as @chrismllr mentioned)?

**Comment by shuowu** [comment] 2020-09-22 19:26
@restfulhead You can also leverage the [refresh-session endpoint](https://developer.okta.com/docs/reference/api/sessions/#refresh-session) to extend it, but you may need to implement some server-side logic for it.

**Comment by jasonrberk** [comment] 2020-10-07 19:11
> Closing as this should be fixed in recent versions. There is a similar but distinct issue with clients that logout via a separate process that is not covered by this issue.

where is #460 referenced in the change log?  https://github.com/okta/okta-auth-js/blob/master/CHANGELOG.md

**Comment by shehrozsheikh** [comment] 2020-12-14 12:07
I am still getting this issue on React, but I figured out that it's because I was using the **Incognito Mode** shifting to the normal mode fixed this issue for me.

**Comment by gmaragao** [comment] 2021-01-20 12:46
@shehrozsheikh
> I am still getting this issue on React, but I figured out that it's because I was using the **Incognito Mode** shifting to the normal mode fixed this issue for me.

Just adding some info here. This is related to third party cookies, which you probably have them disabled when using incognito. If you have third party cookies on any browser/window, it will fail to authenticate.
[More info here](https://support.okta.com/help/s/article/FAQ-How-Blocking-Third-Party-Cookies-Can-Potentially-Impact-Your-Okta-Environment?language=en_US)
