### ISSUE TITLE
Okta-react Login throws error AUTHSDKERROR: the request nonce doesn't match response nonce

### ISSUE THREAD

**Issue by AparnaaKS** [okta/okta-oidc-js#466] opened 2019-05-30 05:49 UTC
Package : "@okta/okta-react": "^1.2.0"

My app uses Okta for authentication and Google as IDP. The app takes me to Google for login. But after login, it takes me back to the ImplicitCallback page and throws AuthSdkError: The request nonce doesnt match response nonce. But on refreshing the home page twice, display successful login with appropriate username.

When try to logout says AuthApiError: Not found : 
![login error](https://user-images.githubusercontent.com/36849675/58611452-c154a500-82cc-11e9-96fc-73a03e4c5f0a.png)
![login on refresh](https://user-images.githubusercontent.com/36849675/58611453-c1ed3b80-82cc-11e9-8667-2c5424cf32de.png)
![logout error](https://user-images.githubusercontent.com/36849675/58611454-c1ed3b80-82cc-11e9-8dfd-f097c531aa47.png)

resource not found : me (session)

**Comment by swiftone** [comment] 2019-05-30 20:59
@AparnaaKS - We've made an update to our developer preview environments, can you see if the issue is still present?

**Comment by swiftone** [comment] 2019-06-19 21:29
Closing as the issue appears to be fixed.  Please reopen or start a new issue if this is not the case.

**Closed by swiftone** 2019-06-19 21:29 UTC
Labels: awaiting-response, bug
