### ISSUE TITLE
signIn not working in react-native

### ISSUE THREAD

**Issue by lakshanboyz** [okta/okta-oidc-js#519] opened 2019-08-06 06:00 UTC
## I'm submitting this issue for the package(s):

- [ ] okta-react-native

## I'm submitting a:

- [ ] Bug report  

## Current behavior

when i try to call signIn function it is not redirecting to okta login page and i can see the following warning in the console 

Possible Unhandled Promise Rejection (id: 3):
ReferenceError: e is not defined
login$@blob:http://localhost:8081/e56d3420-85b3-4743-8bb7-ccac165e2c91:92874:17
tryCatch@blob:http://localhost:8081/e56d3420-85b3-4743-8bb7-ccac165e2c91:41024:19
invoke@blob:http://localhost:8081/e56d3420-85b3-4743-8bb7-ccac165e2c91:41199:24
defineIteratorMethods/</prototype[method]@blob:http://localhost:8081/e56d3420-85b3-4743-8bb7-ccac165e2c91:41067:23
tryCatch@blob:http://localhost:8081/e56d3420-85b3-4743-8bb7-ccac165e2c91:41024:19
invoke@blob:http://localhost:8081/e56d3420-85b3-4743-8bb7-ccac165e2c91:41100:22
callInvokeWithMethodAndArg/<@blob:http://localhost:8081/e56d3420-85b3-4743-8bb7-ccac165e2c91:41130:13
tryCallTwo@blob:http://localhost:8081/e56d3420-85b3-4743-8bb7-ccac165e2c91:45512:7
doResolve@blob:http://localhost:8081/e56d3420-85b3-4743-8bb7-ccac165e2c91:45676:15
Promise@blob:http://localhost:8081/e56d3420-85b3-4743-8bb7-ccac165e2c91:45535:5

## Extra information about the use case/user story you are trying to implement

I am try to develop a react native application with okata authentication

## Environment

- Package Version: @okta/okta-react 1.2.0
- Browser: FireFox
- OS: Ubuntu 18.04.2 LTS
- Node version v10.16.0:
- Other:

**Comment by swiftone** [comment] 2019-08-14 21:43
@lakshanboyz - Thanks for the report.  Unfortunately, we can't diagnose the problem from the vague message.  Can you offer a minimal reproduce case?

**Comment by swiftone** [comment] 2019-08-28 21:25
Closing this due to inaction - if you have more details please feel free to reopen.

**Closed by swiftone** 2019-08-28 21:25 UTC
Labels: awaiting-response

**Comment by pmemids** [comment] 2020-02-14 06:37
on clicking on signIn() its not navigating to okta page
