### ISSUE TITLE
Remove events as a peer dependency (React Native)

### ISSUE THREAD

**Issue by jdnichollsc** [okta/okta-oidc-js#761] opened 2020-04-28 20:25 UTC
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
![image (2)](https://user-images.githubusercontent.com/2154886/80533780-c9491900-8963-11ea-8475-e952eb84e9e9.png)

## Expected behavior
Don't require additional dependencies that are not used from this package.

## Minimal reproduction of the problem with instructions
Clone the below oficial repository, remove `events` as a dependency and run the app https://github.com/okta/samples-js-react-native/blob/master/custom-sign-in/package.json#L18

## Environment

- Package Version: 1.4.0
- OS: macOS Mojave 10.14.6
- Node version (`node -v`): v10.16.3

**Comment by swiftone** [comment] 2020-05-01 19:15
@jdnichollsc - with the changes to resolve the other issues, we do need the events module for the native portion.  Do you have problems if you install it?

**Comment by jdnichollsc** [comment] 2020-05-01 19:47
I can't see any reference of that package from the code 🤔 but I don't have problems with that package 🙂

**Comment by swiftone** [comment] 2020-05-08 18:41
@jdnichollsc - the dependency comes from okta-auth-js, so the references are bit indirect.  

Closing this ticket, but if anyone has further issues or input feel free to open a new ticket with details and reference this one.

**Closed by swiftone** 2020-05-08 18:41 UTC

**Comment by mraible** [comment] 2020-05-08 18:54
@swiftone Are you saying `events` isn't a necessary dependency? I saw it added in the [React Native samples update](https://github.com/okta/samples-js-react-native/commit/82b302de87a1d8d0213bff4899604202aef1d312#diff-82dfaf3197c49c9e708fdebdc4e01c08), so I thought it was needed.

I ask because I'm having issues upgrading OktaDev Schematics to our React Native SDK v1.4.0. You can see my pull request to upgrade [here](https://github.com/oktadeveloper/schematics/pull/300). Build failure is [here](https://travis-ci.org/github/oktadeveloper/schematics/jobs/684554044#L1309). It's weird because I'm unable to reproduce it locally.

**Comment by jdnichollsc** [comment] 2020-05-08 20:34
@swiftone why that package is not included as a dependency of `okta-auth-js`?

**Comment by davidimoore** [comment] 2020-08-31 02:45
I can confirm that I have this issue

**Comment by shuowu** [comment] 2020-08-31 14:45
@jdnichollsc `events` is an internal module for Node environment, but it's not included in the `react-native` env. 
Here is the package that introduces `events` dependency, https://github.com/okta/okta-auth-js/blob/master/package.json#L72 
We can investigate to find an alternative strategy without `events` dependency.

Internal Ref: OKTA-326406

**Comment by shuowu** [comment] 2020-08-31 14:48
@mraible `events` are needed as a peerDependency.
From the travis link in your comment, it looks like it's a test issue, does the following link help ? https://github.com/facebook/jest/issues/6434#issuecomment-525576660

**Comment by jdnichollsc** [comment] 2020-08-31 14:57
Can it be included as a normal dependency?

**Comment by mraible** [comment] 2020-09-01 20:14
@shuowu I tried adding the following in my React Native `Auth-test.js`:

```
describe('auth setup', () => {
  beforeEach(() => {
    jest.useFakeTimers();
  });
  ...
}
```

Unfortunately, this causes things to fail:

```
 FAIL  tests/Auth-test.js (12.116 s)
  ● Console

    console.log

          isomorphic-webcrypto cannot ensure the security of some operations.
          Please eject and run:

              npm install react-native-securerandom --save
              react-native link

          If you'd like not to eject, upvote this feature request:
          https://expo.canny.io/feature-requests/p/crypto-api

      at Object.<anonymous> (node_modules/isomorphic-webcrypto/src/react-native.js:11:11)

  ● authentication flow › should return user profile information from id token

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      126 |   });
      127 |
    > 128 |   it('should return user profile information from id token', async () => {
          |   ^
      129 |     const mockGetIdToken = require('react-native').NativeModules.OktaSdkBridge.getIdToken;
      130 |     mockGetIdToken.mockImplementationOnce(() => {
      131 |       // id_token returns { a: 'b' }

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests/Auth-test.js:128:3)

  ● authentication flow › should return user profile information from getUser method

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      141 |   });
      142 |
    > 143 |   it('should return user profile information from getUser method', async () => {
          |   ^
      144 |     const mockGetUser = require('react-native').NativeModules.OktaSdkBridge.getUser;
      145 |     mockGetUser.mockResolvedValue({ "name": "Mock User" });
      146 |     const wrapper = shallow(<Auth />);

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests/Auth-test.js:143:3)
```

The strange thing is that if I run tests locally, they pass (albeit with errors):

```
➜  SecureApp git:(main) npm test -- -u

> SecureApp@0.0.1 test /Users/mraible/dev/okta/schematics/apps/SecureApp
> jest "-u"


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.get NativeModules [as NativeModules] (node_modules/react-native/index.js:352:12)
      at isAuthenticated$ (node_modules/@okta/okta-react-native/index.js:277:58)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:118:21)
 PASS  tests/App-test.js
  ● Console

    console.log

          isomorphic-webcrypto cannot ensure the security of some operations.
          Please eject and run:

              npm install react-native-securerandom --save
              react-native link

          If you'd like not to eject, upvote this feature request:
          https://expo.canny.io/feature-requests/p/crypto-api

      at Object.<anonymous> (node_modules/isomorphic-webcrypto/src/react-native.js:11:11)

 PASS  tests/Auth-test.js
  ● Console

    console.log

          isomorphic-webcrypto cannot ensure the security of some operations.
          Please eject and run:

              npm install react-native-securerandom --save
              react-native link

          If you'd like not to eject, upvote this feature request:
          https://expo.canny.io/feature-requests/p/crypto-api

      at Object.<anonymous> (node_modules/isomorphic-webcrypto/src/react-native.js:11:11)


Test Suites: 2 passed, 2 total
Tests:       12 passed, 12 total
Snapshots:   1 passed, 1 total
Time:        2.219 s
Ran all test suites.
Execution time: 3 s.
```

However, they [fail in CI](https://github.com/oktadeveloper/schematics/pull/400/checks?check_run_id=1058230074#step:7:1003). Actually, it says that pass, but it's reported as a failure. 

My [`Auth-test.js`](https://github.com/oktadeveloper/schematics/blob/main/src/add-auth/react-native/tests/Auth-test.js) is very similar to [this one in the React Native samples](https://github.com/okta/samples-js-react-native/blob/master/browser-sign-in/__tests__/App-test.js). 

### Steps to reproduce:

```
react-native init SecureApp
cd SecureApp
npm install -g @angular-devkit/schematics-cli
npm i @oktadev/schematics
schematics @oktadev/schematics:add-auth --issuer=$issuer --clientId=$clientId
npm test -- -u
```

**Comment by shuowu** [comment] 2020-09-01 21:09
@mraible the problem might come from https://github.com/oktadeveloper/schematics/blob/main/src/add-auth/react-native/tests/Auth-test.js#L125
I'm not very sure does it work to import/mock module that way. Also, the module name should be `@okta/okta-react-native` instead of `react-native`.

**Comment by mraible** [comment] 2020-09-01 21:15
@I tried changing to `@okta/okta-react-native` and this results in:

```
  ● authentication flow › should return user profile information from id token

    TypeError: Cannot read property 'OktaSdkBridge' of undefined

      127 | 
      128 |   it('should return user profile information from id token', async () => {
    > 129 |     const mockGetIdToken = require('@okta/okta-react-native').NativeModules.OktaSdkBridge.getIdToken;
```

My `setupJest.js` is designed to mock out the Okta React Native SDK.

```js
// Required to correctly polyfill React-Native

import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import { NativeModules } from 'react-native';

configure({ adapter: new Adapter() });

global.XMLHttpRequest = jest.fn();
global.fetch = jest.fn();

if (typeof window !== 'object') {
  global.window = global;
  global.window.navigator = {};
}

NativeModules.OktaSdkBridge = {
  createConfig: jest.fn(),
  signIn: jest.fn(),
  signOut: jest.fn(),
  getAccessToken: jest.fn(),
  getIdToken: jest.fn(),
  getUser: jest.fn(),
  isAuthenticated: jest.fn(),
  revokeAccessToken: jest.fn(),
  revokeIdToken: jest.fn(),
  revokeRefreshToken: jest.fn(),
  introspectAccessToken: jest.fn(),
  introspectIdToken: jest.fn(),
  introspectRefreshToken: jest.fn(),
  refreshTokens: jest.fn(),
};

```
