### ISSUE TITLE
Okta-React fails with React-Router-Dom >v4.3.1

### ISSUE THREAD

**Issue by myrtleTree33** [okta/okta-oidc-js#414] opened 2019-03-24 13:54 UTC
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
okta-react crashes React Router for `>v4.3.1`.  I have confirmed this to work with React-Router-Dom `v4.2.2`.

## Expected behavior
It should work with latest Router install.

## Minimal reproduction of the problem with instructions

<img width="1320" alt="Screenshot 2019-03-24 at 9 50 04 PM" src="https://user-images.githubusercontent.com/1506937/54880413-4069cf00-4e7f-11e9-88d5-520ea6a3443d.png">

## Extra information about the use case/user story you are trying to implement
NA

## Environment

- Package Version:
- Browser:
- OS: Mac OS
- Node version (`node -v`):
- Other:

**Comment by swiftone** [comment] 2019-03-29 20:37
Same root cause as https://github.com/okta/okta-oidc-js/issues/401 

Closing this one, tracking further updates on the other issue.

**Closed by swiftone** 2019-03-29 20:37 UTC
