### ISSUE TITLE
Can't resolve '../config' on fresh Okta Angular install

### ISSUE THREAD

**Issue by keisenb** [okta/okta-oidc-js#602] opened 2019-11-14 04:37 UTC
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [*] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [*] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Running ng serve on a fresh angular project with okta angular added results in the following error message

```
ERROR in ./node_modules/@okta/okta-auth-js/lib/browser/browser.js
Module not found: Error: Can't resolve '../config' in '/Users/eisenbk/git/project/node_modules/@okta/okta-auth-js/lib/browser'
ERROR in ./node_modules/@okta/okta-auth-js/lib/browser/browserStorage.js
Module not found: Error: Can't resolve '../config' in '/Users/eisenbk/git/project/node_modules/@okta/okta-auth-js/lib/browser'
ERROR in ./node_modules/@okta/okta-auth-js/lib/tx.js
Module not found: Error: Can't resolve './config' in '/Users/eisenbk/git/project/node_modules/@okta/okta-auth-js/lib'
ERROR in ./node_modules/@okta/okta-auth-js/lib/TokenManager.js
Module not found: Error: Can't resolve './config' in '/Users/eisenbk/git/project/node_modules/@okta/okta-auth-js/lib'
ERROR in ./node_modules/@okta/okta-auth-js/lib/token.js
Module not found: Error: Can't resolve './config' in '/Users/eisenbk/git/project/node_modules/@okta/okta-auth-js/lib'
ERROR in ./node_modules/@okta/okta-auth-js/lib/http.js
Module not found: Error: Can't resolve './config' in '/Users/eisenbk/git/project/node_modules/@okta/okta-auth-js/lib'
```

## Expected behavior

Run ng serve successfully without an error message

## Minimal reproduction of the problem with instructions

1. ng new okta-sample
2. npm install @okta/okta-angular --save
3. Add the following to your app.module.ts

```
import { OKTA_CONFIG, OktaAuthModule } from '@okta/okta-angular';

const config = {
  issuer: 'issuer here',
  redirectUri: 'http://localhost:4200/implicit/callback',
  clientId: 'client id here',
  pkce: true
};

imports: [
  ...
  OktaAuthModule.initAuth(config),
],
providers: [
  { provide: OKTA_CONFIG, useValue: config }
],
```

## Extra information about the use case/user story you are trying to implement

Digging into the dependencies a bit I can see that the okta angular library is dependent on the okta-auth-js library. The version of okta-auth-js that gets installed is 2.10.0. According to npm this was just released 2 hours ago so I'm wondering if a breaking change was introduced here...

I happen to have the demo okta angular project locally that I installed yesterday successfully. It was using the okta-auth-js library @ v2.7.0 and okta-angular @ v1.2.2

## Environment

- Package Version: Okta Angular @ 1.2.2
- Browser: Chrome
- OS: Mac OSX 10.15.1
- Node version (`node -v`): v12.4.0
- Other:

**Comment by gennadiy-dubina** [comment] 2019-11-14 15:55
any workarounds?

**Comment by Zzarek** [comment] 2019-11-14 16:10
@keisenb 

I was having this problem last night when I installed. I'm moving an app from AzureAD to Okta and this stopped me in my tracks.  Perhaps that was right the changeset as well.

Its being discussed here: https://github.com/okta/okta-auth-js/issues

@gennadiy-dubina 
There seems to be discussion of a workaround: https://github.com/okta/okta-auth-js/issues/278

**Comment by swiftone** [comment] 2019-11-14 17:34
@Zzarek - Thanks for the accurate summary!

@keisenb - Thanks for the accurate report.   We've confirmed the issue as you suspected: we published a new version of @okta/okta-auth-js yesterday and somehow that publish wasn't our full update.  Reverting back to 2.0.9 of @okta/okta-auth-js can workaround the issue, and we're publishing an update just as soon as we are confident that we've fully nailed the problem.

Since the packages in this repo is impacted by the bug, I'm leaving this issue open for now and we'll close it out after updating, but please see the earliest report (https://github.com/okta/okta-auth-js/issues/275 ) for any discussion.

**Comment by keisenb** [comment] 2019-11-14 17:56
Awesome thanks for the quick response. I will downgrade for now until I see a fix. Thanks!

**Comment by ssolovyev** [comment] 2019-11-14 18:56
This [one](https://github.com/okta/okta-auth-js/issues/280) is also related - I've already got a workaround [here](https://github.com/okta/okta-auth-js/issues/278#issuecomment-553955446).

**Comment by swiftone** [comment] 2019-11-14 23:04
@okta/okta-auth-js 2.10.1 has been published to npm, which should address this error.  This error resulted from a problem where our build system released an incorrect version.

We apologize for any inconvenience, and thank you for your patience, with particular thanks to the developers that reported the bug and helped each other with workarounds.

**Closed by swiftone** 2019-11-14 23:04 UTC
