### ISSUE TITLE
Not getting user info even after authenticated after login

### ISSUE THREAD

**Issue by lawchihon** [okta/okta-oidc-js#717] opened 2020-03-26 04:15 UTC
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [X] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

When trying to run the code of following, sometimes it failed to get the user info.
It works most of the time right after login, but not after logged in for a while without any activity.
In that case, after refreshing the page, `this.oktaAuth.getUser()` just return empty.

## Expected behavior

Get user info whenever authenticated

## Minimal reproduction of the problem with instructions

```
    this.oktaAuth.$authenticationState.subscribe(
      (isAuthenticated) => {
	    if (isAuthenticated) {
	      const user = await this.oktaAuth.getUser();
	      if (user) {
	      	console.log(user);
	      } else {
	      	console.log('no user');
	      }
	    }
      },
      (err) => {
        console.log(err);
      }
    );
```
In that case, it will log `no user`

## Environment

- Package Version: 2.0.0
- Browser: Chrome
- OS: Mac
- Node version (node -v): v12.13.1
- Other:

**Comment by LongJohnSilver1504** [comment] 2020-03-26 13:34
Hi @lawchihon check this,https://github.com/okta/okta-oidc-js/issues/656, in resume:
`The original problem may have been due to a race with handleAuthentication() which is usually called by the callback component. It takes a small amount of time to process the tokens returned from the server and place them into local storage.`(Thanks to @aarongranick-okta).
They suggest use v2 , that  solve the problem for me :)

**Comment by lawchihon** [comment] 2020-03-26 16:15
Hello @LongJohnSilver1504 , thanks for your reply. But I think the situation is a bit different with the ticket mentioned. In fact, the `getUser` is working perfect after sign in. It is only the problem after signed in for a while without any activity. Also, I'm not sure if the fix for that also apply to the angular. As I'm already using v2 of the okta-angular.

**Comment by swiftone** [comment] 2020-03-27 21:08
@lawchihon - Thanks for the report.

How long a period of inactivity?  We're assuming (at this point) the sequence of events is:
- your okta tokens are NOT expired
- your okta session (on the issuer domain) IS expired (or the cookies removed from the browser)

The client has no way of knowing the okta session does not exist until a call is made (and the lack of a session in no way invalidates your id/access tokens).

Can you say what happens on the network call made when the getUser is called (/userinfo, I believe)?  Status code, any error messages, etc.

**Comment by lawchihon** [comment] 2020-03-30 22:44
@swiftone , I checked the network call but don't see any request for `/userinfo`. I added catch block for `getUser()` but still nothing get logged. The result from `getUser()` is just `undefined`.

**Comment by glubb92** [comment] 2020-03-31 16:28
Facing exactly the same issue (using react), `isAuthenticated` is returning true, but `getUser` is returning undefined.
Only occurs after some inactivity. I also can't see the `/userinfo` request in my network tab.

Got some complains over the last few days from customers, until I finally could reproduce it now .... kinda critical in my opinion!

As a workaround, I am checking for `isAuthenticated` and if `getUser()`is returning not undefined, otherwise I'll logout the user manually.

**Comment by swiftone** [comment] 2020-04-03 20:32
@glubb92 - I suspect your issue will be fixed when https://github.com/okta/okta-oidc-js/pull/723 is merged, as it sounds like you have a token expiring that isn't being noticed.

Do you have `autoRenew: false` set?

**Comment by swiftone** [comment] 2020-04-10 20:34
@glubb92 - if your accessTokens and idTokens have different expiration lifetimes, you might have the case where isAuthenticated will be true (accessToken is still valid) but getUser() will not be happy (idToken is not valid)

Try checking for the idToken before calling getUser and let us know if that is related to your issue.

**Comment by lawchihon** [comment] 2020-04-15 02:41
@swiftone I tried to check the idToken by calling `oktaAuth.getIdToken()`, but it is also returning `undefined`

**Comment by swiftone** [comment] 2020-04-17 19:02
Potentially related to https://github.com/okta/okta-oidc-js/issues/744 - idToken should be autorenewing

**Comment by blake-mealey** [comment] 2020-05-06 16:03
I am also having this issue using the @okta/okta-react package. When do you estimate the fix will be in production?

**Comment by hartvix** [comment] 2020-08-19 16:10
I am experiencing the same problem with @okta/okta-react as well.

**Comment by shuowu** [comment] 2020-08-19 16:23
@blake-mealey @hartvix In current okta-react, the SDK will think the app `isAuthenticated` when at least one of the tokens (idToken, accessToken) is available. I suspect you are running into a scenario where idToken is removed from storage, but the accessToken is still sit there. Then the SDK ran into this [block of code](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/src/AuthService.js#L161), and returned `undefined`.

A workaround I would suggest is to override the `isAuthenticated` callback in options to make sure the SDK always check on both tokens for `isAuthenticated` state.
```js
const authService = new AuthService({
  // ...other configs
  isAuthenticated: async () => {
    const idToken = await authService.getTokenManager().get('idToken');
    const accessToken = await authService.getTokenManager().get('accessToken');
    return !!(idToken && accessToken);
  }
});
<Security authService={authService} />
```

**Comment by shuowu** [comment] 2020-08-19 16:25
Internal Ref: OKTA-323720

**Comment by hartvix** [comment] 2020-08-20 15:22
@shuowu Thanks, that workaround works. However, am I right in assuming that after an hour of inactivity and a page refresh, the user will have to log in again (since id tokens are restricted to one hour lifetime)? Or am I missing some trick to keep the user login alive?

**Comment by shuowu** [comment] 2020-08-20 17:04
@hartvix Yes, the assumption is correct. Since right now there is no `authJs` instance exposed from `react-sdk`, what you can use is only the `AuthService` instance, which has bug now. 

Two workaround suggestions before the office bugfix release if you don't want the user login too frequently:
- Extend your session expiration time in the okta developer console. `Applications -> {your app} -> Sign on -> Sign on policy -> Add rule -> Actions -> Prompt for re-authentication`
- Still use the default `isAuthenticated` callback behavior, then add customized logic in your app to persist the idToken after the user login. Then read information from it. (**NOTE**: userinfo maybe stale with this approach)

**Comment by aarongranick-okta** [comment] 2021-01-14 22:47
We believe this issue has been resolved in current versions of `okta-angular` and `okta-react`

If you are experiencing a similar issue,
`okta-angular`, create an issue here: https://github.com/okta/okta-angular
`okta-react` create an issue here: https://github.com/okta/okta-react

**Closed by aarongranick-okta** 2021-01-14 22:47 UTC
