### ISSUE TITLE
@okta/angular-angular: AuthSdkError: OAuth flow response state doesn't match request state

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-js#140] opened 2018-03-08 04:24 UTC
I've recreated my [Spring Boot 2.0 + Angular 5](https://developer.okta.com/blog/2017/12/04/basic-crud-angular-and-spring-boot) tutorial a couple time tonight and I've gotten this error twice in a row:

```
webpack-internal:///./node_modules/@angular/core/esm5/core.js:1664 ERROR Error: Uncaught (in promise): AuthSdkError: OAuth flow response state doesn't match request state
Error
    at eval (webpack-internal:///./node_modules/@okta/okta-auth-js/lib/errors/AuthSdkError.js:26)
    at Object../node_modules/@okta/okta-auth-js/lib/errors/AuthSdkError.js (vendor.bundle.js:583)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (webpack-internal:///./node_modules/@okta/okta-auth-js/lib/storageBuilder.js:1)
    at Object../node_modules/@okta/okta-auth-js/lib/storageBuilder.js (vendor.bundle.js:625)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (webpack-internal:///./node_modules/@okta/okta-auth-js/lib/storageUtil.js:2)
    at Object../node_modules/@okta/okta-auth-js/lib/storageUtil.js (vendor.bundle.js:632)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (webpack-internal:///./node_modules/@okta/okta-auth-js/lib/http.js:4)
    at eval (webpack-internal:///./node_modules/@okta/okta-auth-js/lib/errors/AuthSdkError.js:26)
    at Object../node_modules/@okta/okta-auth-js/lib/errors/AuthSdkError.js (vendor.bundle.js:583)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (webpack-internal:///./node_modules/@okta/okta-auth-js/lib/storageBuilder.js:1)
    at Object../node_modules/@okta/okta-auth-js/lib/storageBuilder.js (vendor.bundle.js:625)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (webpack-internal:///./node_modules/@okta/okta-auth-js/lib/storageUtil.js:2)
    at Object../node_modules/@okta/okta-auth-js/lib/storageUtil.js (vendor.bundle.js:632)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (webpack-internal:///./node_modules/@okta/okta-auth-js/lib/http.js:4)
    at resolvePromise (webpack-internal:///./node_modules/zone.js/dist/zone.js:809)
    at eval (webpack-internal:///./node_modules/zone.js/dist/zone.js:728)
    at rejected (webpack-internal:///./node_modules/@okta/okta-angular/dist/okta/okta.service.js:24)
    at ZoneDelegate.invoke (webpack-internal:///./node_modules/zone.js/dist/zone.js:388)
    at Object.onInvoke (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4965)
    at ZoneDelegate.invoke (webpack-internal:///./node_modules/zone.js/dist/zone.js:387)
    at Zone.run (webpack-internal:///./node_modules/zone.js/dist/zone.js:138)
    at eval (webpack-internal:///./node_modules/zone.js/dist/zone.js:858)
    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:421)
    at Object.onInvokeTask (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4956)
defaultErrorLogger @ webpack-internal:///./node_modules/@angular/core/esm5/core.js:1664
```

I'm not sure what's causing it. Here's my `package.json`:

```json
{
  "name": "client",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.2.4",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.4",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@okta/okta-angular": "0.0.13",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.2",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
```

**Comment by mraible** [comment] 2018-03-08 04:45
If I copy the [`package-lock.json`](https://github.com/oktadeveloper/okta-spring-boot-2-angular-5-example/blob/master/client/package-lock.json) from the aforementioned sample app, it works.

**Comment by mraible** [comment] 2018-03-08 05:02
This appears to be caused by Angular 5.2.8. If I change my `package.json` to hard-code `5.2.7`, it all works. 

```
{
  "name": "client",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "5.2.7",
    "@angular/cdk": "^5.2.4",
    "@angular/common": "5.2.7",
    "@angular/compiler": "5.2.7",
    "@angular/core": "5.2.7",
    "@angular/forms": "5.2.7",
    "@angular/http": "5.2.7",
    "@angular/material": "^5.2.4",
    "@angular/platform-browser": "5.2.7",
    "@angular/platform-browser-dynamic": "5.2.7",
    "@angular/router": "5.2.7",
    "@okta/okta-angular": "0.0.13",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.2",
    "@angular/compiler-cli": "5.2.7",
    "@angular/language-service": "5.2.7",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
```

**Comment by mraible** [comment] 2018-03-08 05:13
I was able to prove that this is the problem by performing the following steps:

```
git clone https://github.com/oktadeveloper/okta-spring-boot-2-angular-5-example
cd okta-spring-boot-2-angular-5-example/client
rm package-lock.json
npm i
ng serve
```

You will likely have to change your `clientId` in `client/src/app/app.module.ts` to be a valid clientId since I deleted my app that's currently in GitHub. After you've set that, you'll see the error when you run `ng serve` and try to login at `http://localhost:4200`.

Here's the diff for `package-lock.json` if I remove it, then run `npm install`.

```diff
diff --git a/package-lock.json b/package-lock.json
index 3787739..2bc7b41 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -61,32 +61,32 @@
       }
     },
     "@angular/animations": {
-      "version": "5.2.7",
-      "resolved": "https://registry.npmjs.org/@angular/animations/-/animations-5.2.7.tgz",
-      "integrity": "sha512-t/B0z2OYO+yy8SJKB1/evSNPvnLsl+AclhM1p21/NnETxQUqvct1KXeDM7nYDu5hmnGmuavhua8LDo6rN5zS+Q==",
+      "version": "5.2.8",
+      "resolved": "https://registry.npmjs.org/@angular/animations/-/animations-5.2.8.tgz",
+      "integrity": "sha512-VfHN7ICR9QBaEbA02ip7ipNjD6m9ayfsliIE/ACkTVevObEdL90T3Q/NxiX+JRZSDL09M9XopIi1/WOeOn6Evw==",
       "requires": {
         "tslib": "1.9.0"
       }
     },
     "@angular/cdk": {
-      "version": "5.2.3",
-      "resolved": "https://registry.npmjs.org/@angular/cdk/-/cdk-5.2.3.tgz",
-      "integrity": "sha512-o95vQCJ1FpHLQj/ZfIrOya/rK0S7VwiY5vjEivpFnH25kHF5LNT4LTj6BOFkPbClMHTIM2wdKwWnuTfK0bg9WA==",
+      "version": "5.2.4",
+      "resolved": "https://registry.npmjs.org/@angular/cdk/-/cdk-5.2.4.tgz",
+      "integrity": "sha1-wKQpqHENj+2xV/VG4hy0nUM19/c=",
       "requires": {
         "tslib": "1.9.0"
       }
     },
     "@angular/cli": {
-      "version": "1.7.2",
-      "resolved": "https://registry.npmjs.org/@angular/cli/-/cli-1.7.2.tgz",
-      "integrity": "sha512-U0RXiG6rNe5GqZazn+FLy3p4rOhBwpf5NWAec/JKe+u/cekIsyeDXLfqGJwzLhMEV4Iv2k4i3o5imejkEc4A9g==",
+      "version": "1.7.3",
+      "resolved": "https://registry.npmjs.org/@angular/cli/-/cli-1.7.3.tgz",
+      "integrity": "sha512-19sh0SbjneG7/R/FvZBfHsHqfIqyj4LQuXdddJKMCDM97UoHQTjfgrpRvBf3a3lR79wdLXchWJBD9Yc6ifosEA==",
       "dev": true,
       "requires": {
         "@angular-devkit/build-optimizer": "0.3.2",
         "@angular-devkit/core": "0.3.2",
         "@angular-devkit/schematics": "0.3.2",
         "@ngtools/json-schema": "1.2.0",
-        "@ngtools/webpack": "1.10.1",
+        "@ngtools/webpack": "1.10.2",
         "@schematics/angular": "0.3.2",
         "@schematics/package-update": "0.3.2",
         "ajv": "6.2.1",
@@ -94,7 +94,7 @@
         "cache-loader": "1.2.2",
         "chalk": "2.2.2",
         "circular-dependency-plugin": "4.4.0",
-        "clean-css": "4.1.9",
+        "clean-css": "4.1.11",
         "common-tags": "1.7.2",
         "copy-webpack-plugin": "4.4.3",
         "core-object": "3.1.5",
@@ -144,25 +144,25 @@
       }
     },
     "@angular/common": {
-      "version": "5.2.7",
-      "resolved": "https://registry.npmjs.org/@angular/common/-/common-5.2.7.tgz",
-      "integrity": "sha512-TqsDMmPX1JlEH2QIneuAVzEO4ubzxLBAdV4XbKWDQKC/UfbWIIpSrSp2cIi85NV1tKkg0WAaodCIZ02NucHIHg==",
+      "version": "5.2.8",
+      "resolved": "https://registry.npmjs.org/@angular/common/-/common-5.2.8.tgz",
+      "integrity": "sha512-vHODEZPDtBU5b7a2GjtQYPYmCPRq5FQsJp696pebGMJEZdvN/Du43z8V7lWEdBBLGD+oNXX6rXGD9Pr4P/Bg9w==",
       "requires": {
         "tslib": "1.9.0"
       }
     },
     "@angular/compiler": {
-      "version": "5.2.7",
-      "resolved": "https://registry.npmjs.org/@angular/compiler/-/compiler-5.2.7.tgz",
-      "integrity": "sha512-26RG+Dy+M/95OyNNqM+OAruarIPOmbndiaglz2dMrNYzenfbSgG/AoPlL5uCdSqZDiXgnlKnS2K6/ePWXDSKNw==",
+      "version": "5.2.8",
+      "resolved": "https://registry.npmjs.org/@angular/compiler/-/compiler-5.2.8.tgz",
+      "integrity": "sha512-xFqY7LDt/LGo6zaYzUwDRGq6Dm2Q9Z2R86ZNdy5wYRzMP+qLnwwENbU74YailKlt02WNtp83R1fdRDDlKI8N+Q==",
       "requires": {
         "tslib": "1.9.0"
       }
     },
     "@angular/compiler-cli": {
-      "version": "5.2.7",
-      "resolved": "https://registry.npmjs.org/@angular/compiler-cli/-/compiler-cli-5.2.7.tgz",
-      "integrity": "sha512-91gQolzsKyOlmBNW1J7lyu+dXHe/KHbAXU459hn6rycMHuTt60XvxA5O3xy3Pqt28VgbOOSrQfq5eVjZodKjWg==",
+      "version": "5.2.8",
+      "resolved": "https://registry.npmjs.org/@angular/compiler-cli/-/compiler-cli-5.2.8.tgz",
+      "integrity": "sha512-u0cUfpbU2VNmRfkSS/tlsAzF24/LdlXqv8RFFLReJhwZTv4mKl1DzSjvOf6kfALGHDqCdHsVWcx2YJ8f6CeCMg==",
       "dev": true,
       "requires": {
         "chokidar": "1.7.0",
@@ -180,63 +180,63 @@
       }
     },
     "@angular/core": {
-      "version": "5.2.7",
-      "resolved": "https://registry.npmjs.org/@angular/core/-/core-5.2.7.tgz",
-      "integrity": "sha512-DQuL6n7cjBfZmWX5RCV271g6PW9N8b93g2skWnM/zjm+BL9tfHPgvmsjMNB7QEHSxW8VBaaQ6gjj422O01A87g==",
+      "version": "5.2.8",
+      "resolved": "https://registry.npmjs.org/@angular/core/-/core-5.2.8.tgz",
+      "integrity": "sha512-exvh2OY+WDm90bgzZ89Asi2nZc2zrg/OWJuKMbxNfA6nxnyjCQ7uGRjTGr+MOynG+vd54J2Evtg2eDPdbcNg5A==",
       "requires": {
         "tslib": "1.9.0"
       }
     },
     "@angular/forms": {
-      "version": "5.2.7",
-      "resolved": "https://registry.npmjs.org/@angular/forms/-/forms-5.2.7.tgz",
-      "integrity": "sha512-43oLKdzMjMV/hOLpSTg8aOggcx+veTnPp/JN+KzMGo2qtbim5nk3fnuscWDeDOdkh8hPRPGarKxeFNEE9ZZSTg==",
+      "version": "5.2.8",
+      "resolved": "https://registry.npmjs.org/@angular/forms/-/forms-5.2.8.tgz",
+      "integrity": "sha512-yxpFwZcek7259O1+4p1Zfd8FOEJs8lh6T8n2W7IBT8Q1pcAMBCYfMi/Xga69AbypFIy3P+V6DaJoq8ZZgpwefg==",
       "requires": {
         "tslib": "1.9.0"
       }
     },
     "@angular/http": {
-      "version": "5.2.7",
-      "resolved": "https://registry.npmjs.org/@angular/http/-/http-5.2.7.tgz",
-      "integrity": "sha512-048+tCbsNYc9xVvIn5/sOvO4fXVkbB5b1IRYRGiRYXpTz6+JWIm5AwOqZIOeVDgqgZHFf96QllXDcFbdNVDgSA==",
+      "version": "5.2.8",
+      "resolved": "https://registry.npmjs.org/@angular/http/-/http-5.2.8.tgz",
+      "integrity": "sha512-vtrO7RLN9v7adVrs/neWStmrCH6+4gm1gYqUYfl6BIYnazACMleqIeAagTbTD08oMblx2dU17NRNbD+2qL8q5A==",
       "requires": {
         "tslib": "1.9.0"
       }
     },
     "@angular/language-service": {
-      "version": "5.2.7",
-      "resolved": "https://registry.npmjs.org/@angular/language-service/-/language-service-5.2.7.tgz",
-      "integrity": "sha512-Tqd9ll6QBSKa2PKzhbyRiKfKZh4MOB6um3aiedC+m3IBB8zMgrY+EJbfP/SN52LsZdShEnLjuKcBZG0eqTjgEQ==",
+      "version": "5.2.8",
+      "resolved": "https://registry.npmjs.org/@angular/language-service/-/language-service-5.2.8.tgz",
+      "integrity": "sha512-MEEi1jB7oJgJxHmSDkwlu4Fm1bSU5TpkE3ideqO8ollxPbMgNOYNwH/9Gm634qPD+rvQaeXywKLQ0i+LQQlYiA==",
       "dev": true
     },
     "@angular/material": {
-      "version": "5.2.3",
-      "resolved": "https://registry.npmjs.org/@angular/material/-/material-5.2.3.tgz",
-      "integrity": "sha512-v6IGxGWaeALgBH8+kt2Q9K32zmJQH193bWdCeWmtXk0vJlj3NTiWYy+vLoZQ8aPIAtOqCKCmhf5VrerkS6pgww==",
+      "version": "5.2.4",
+      "resolved": "https://registry.npmjs.org/@angular/material/-/material-5.2.4.tgz",
+      "integrity": "sha1-noI3mDJCg9I+qDkVb6xby3NEPVU=",
       "requires": {
         "tslib": "1.9.0"
       }
     },
     "@angular/platform-browser": {
-      "version": "5.2.7",
-      "resolved": "https://registry.npmjs.org/@angular/platform-browser/-/platform-browser-5.2.7.tgz",
-      "integrity": "sha512-SdLx4F6tOy4/s3y1KZ/Z3YA6fiIrydaO2bry2FJglDxJh24p6TZIob+zC16N2MTuFW819KY5OlacNhc8aj6Yag==",
+      "version": "5.2.8",
+      "resolved": "https://registry.npmjs.org/@angular/platform-browser/-/platform-browser-5.2.8.tgz",
+      "integrity": "sha512-f0tONG8+ZQOiv5/hLY76Sl1/BY6AR8Zt4buf2klz7zba5SxKLZwcsk6OfJC2PA0WtlJGiz7cSjbPr0B5sZKv8w==",
       "requires": {
         "tslib": "1.9.0"
       }
     },
     "@angular/platform-browser-dynamic": {
-      "version": "5.2.7",
-      "resolved": "https://registry.npmjs.org/@angular/platform-browser-dynamic/-/platform-browser-dynamic-5.2.7.tgz",
-      "integrity": "sha512-95Rwf1JcGF/BI48k+VG2moLTVC863jPSjmHaGkz7cA9bi/QrRFGvFghl1qIm4Ezp3dj8CH8TE3TWB+1AmAg3AQ==",
+      "version": "5.2.8",
+      "resolved": "https://registry.npmjs.org/@angular/platform-browser-dynamic/-/platform-browser-dynamic-5.2.8.tgz",
+      "integrity": "sha512-FzHVZf5XMty0v+hnWOU5PsXexlebvW4+EhfGG85vWCM/M9y0bF3ZSmdqZoXfGO8/Px2JbcBx0r3+GKUgsCieMA==",
       "requires": {
         "tslib": "1.9.0"
       }
     },
     "@angular/router": {
-      "version": "5.2.7",
-      "resolved": "https://registry.npmjs.org/@angular/router/-/router-5.2.7.tgz",
-      "integrity": "sha512-ppl0X7EfEgKYXIEPtdy8cOKj5KXuwCQ5Ila+IuGnSjKIRXt/olhBLJMprVl1VJgoxXj7z2i14U7kKaqSvGtpXw==",
+      "version": "5.2.8",
+      "resolved": "https://registry.npmjs.org/@angular/router/-/router-5.2.8.tgz",
+      "integrity": "sha512-v4k1eUpauO8z/q9kcjr+vDhLvvGw5MzctJJQRoObqLhckFGBmAoITfEFsbF1ejsd/nqa9i+ivxe+LB00evbFXw==",
       "requires": {
         "tslib": "1.9.0"
       }
@@ -248,9 +248,9 @@
       "dev": true
     },
     "@ngtools/webpack": {
-      "version": "1.10.1",
-      "resolved": "https://registry.npmjs.org/@ngtools/webpack/-/webpack-1.10.1.tgz",
-      "integrity": "sha512-Pa2FUy9n2Pu7kkTho6ADfHyypTmDMY8/HT7y9G3tZdaEsS7CjFMdchN5Dx+TCATGVh+G6FLS2mjgXBiGVTmbWw==",
+      "version": "1.10.2",
+      "resolved": "https://registry.npmjs.org/@ngtools/webpack/-/webpack-1.10.2.tgz",
+      "integrity": "sha512-3u2zg2rarG3qNLSukBClGADWuq/iNn5SQtlSeAbfKzwBeyLGbF0gN1z1tVx1Bcr8YwFzR6NdRePQmJGcoqq1fg==",
       "dev": true,
       "requires": {
         "chalk": "2.2.2",
@@ -388,9 +388,9 @@
       }
     },
     "acorn": {
-      "version": "5.5.0",
-      "resolved": "https://registry.npmjs.org/acorn/-/acorn-5.5.0.tgz",
-      "integrity": "sha512-arn53F07VXmls4o4pUhSzBa4fvaagPRe7AVZ8l7NHxFWUie2DsuFSBMMNAkgzRlOhEhzAnxeKyaWVzOH4xqp/g==",
+      "version": "5.5.1",
+      "resolved": "https://registry.npmjs.org/acorn/-/acorn-5.5.1.tgz",
+      "integrity": "sha512-D/KGiCpM/VOtTMDS+wfjywEth926WUrArrzYov4N4SI7t+3y8747dPpCmmAvrm/Z3ygqMHnyPxvYYO0yTdn/nQ==",
       "dev": true
     },
     "acorn-dynamic-import": {
@@ -416,7 +416,7 @@
       "integrity": "sha512-efP54n3d1aLfjL2UMdaXa6DsswwzJeI5rqhbFvXMrKiJ6eJFpf+7R0zN7t8IC+XKn2YOAFAv6xbBNgHUkoHWLw==",
       "dev": true,
       "requires": {
-        "acorn": "5.5.0",
+        "acorn": "5.5.1",
         "xtend": "4.0.1"
       }
     },
@@ -821,7 +821,7 @@
       "dev": true,
       "requires": {
         "browserslist": "2.11.3",
-        "caniuse-lite": "1.0.30000812",
+        "caniuse-lite": "1.0.30000813",
         "normalize-range": "0.1.2",
         "num2fraction": "1.2.2",
         "postcss": "6.0.19",
@@ -1476,8 +1476,8 @@
       "integrity": "sha512-yWu5cXT7Av6mVwzWc8lMsJMHWn4xyjSuGYi4IozbVTLUOEYPSagUB8kiMDUHA1fS3zjr8nkxkn9jdvug4BBRmA==",
       "dev": true,
       "requires": {
-        "caniuse-lite": "1.0.30000812",
-        "electron-to-chromium": "1.3.34"
+        "caniuse-lite": "1.0.30000813",
+        "electron-to-chromium": "1.3.36"
       }
     },
     "buffer": {
@@ -1640,9 +1640,9 @@
       }
     },
     "caniuse-lite": {
-      "version": "1.0.30000812",
-      "resolved": "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30000812.tgz",
-      "integrity": "sha512-j+l55ayQ9BO4Sy9iVfbf99+G+4ddAmkXoiEt73WCW4vJ83usrlHzDkFEnNXe5/swkVqE7YBm5i8M2uRXlx9vWg==",
+      "version": "1.0.30000813",
+      "resolved": "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30000813.tgz",
+      "integrity": "sha512-A8ITSmH5SFdMFdC704ggjg+x2z5PzQmVlG8tavwnfvbC33Q1UYrj0+G+Xm0SNAnd4He36fwUE/KEWytOEchw+A==",
       "dev": true
     },
     "caseless": {
@@ -1804,9 +1804,9 @@
       }
     },
     "clean-css": {
-      "version": "4.1.9",
-      "resolved": "https://registry.npmjs.org/clean-css/-/clean-css-4.1.9.tgz",
-      "integrity": "sha1-Nc7ornaHpJuYA09w3gDE7dOCYwE=",
+      "version": "4.1.11",
+      "resolved": "https://registry.npmjs.org/clean-css/-/clean-css-4.1.11.tgz",
+      "integrity": "sha1-Ls3xRaujj1R0DybO/Q/z4D4SXWo=",
       "dev": true,
       "requires": {
         "source-map": "0.5.7"
@@ -2182,7 +2182,7 @@
       "dev": true,
       "requires": {
         "is-directory": "0.3.1",
-        "js-yaml": "3.10.0",
+        "js-yaml": "3.11.0",
         "minimist": "1.2.0",
         "object-assign": "4.1.1",
         "os-homedir": "1.0.2",
@@ -2603,7 +2603,7 @@
       "integrity": "sha512-H6PmeeUcZloWtdt4DAkFyzFL94arpHr3NOwwmVILFiy+9Qd4JTxxXrzfyGk/lmct2qVGBwTSwSXagqu2BxmWig==",
       "dev": true,
       "requires": {
-        "acorn": "5.5.0",
+        "acorn": "5.5.1",
         "defined": "1.0.0"
       }
     },
@@ -2794,9 +2794,9 @@
       "dev": true
     },
     "electron-to-chromium": {
-      "version": "1.3.34",
-      "resolved": "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.3.34.tgz",
-      "integrity": "sha1-2TSY9AORuwwWpgPYJBuZUUBBV+0=",
+      "version": "1.3.36",
+      "resolved": "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.3.36.tgz",
+      "integrity": "sha1-Dqv3Gp6+qQE/scw1o5DgaGJPJ+g=",
       "dev": true
     },
     "elliptic": {
@@ -5077,9 +5077,9 @@
       }
     },
     "hosted-git-info": {
-      "version": "2.5.0",
-      "resolved": "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.5.0.tgz",
-      "integrity": "sha512-pNgbURSuab90KbTqvRPsseaTxOJCZBD0a7t+haSN33piP9cCM4l0CqdzAif2hUqm716UovKB2ROmiabGAKVXyg==",
+      "version": "2.6.0",
+      "resolved": "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.6.0.tgz",
+      "integrity": "sha512-lIbgIIQA3lz5XaB6vxakj6sDHADJiZadYEJB+FgA+C4nubM1NwcuvUr9EJPmnH1skZqpqUzWborWo8EIUi0Sdw==",
       "dev": true
     },
     "hpack.js": {
@@ -5107,7 +5107,7 @@
       "dev": true,
       "requires": {
         "camel-case": "3.0.0",
-        "clean-css": "4.1.9",
+        "clean-css": "4.1.11",
         "commander": "2.14.1",
         "he": "1.1.1",
         "ncname": "1.0.0",
@@ -5230,9 +5230,9 @@
       }
     },
     "http-parser-js": {
-      "version": "0.4.10",
-      "resolved": "https://registry.npmjs.org/http-parser-js/-/http-parser-js-0.4.10.tgz",
-      "integrity": "sha1-ksnBN0w1CF912zWexWzCV8u5P6Q=",
+      "version": "0.4.11",
+      "resolved": "https://registry.npmjs.org/http-parser-js/-/http-parser-js-0.4.11.tgz",
+      "integrity": "sha512-QCR5O2AjjMW8Mo4HyI1ctFcv+O99j/0g367V3YoVnrNw5hkDvAWZD0lWGcc+F4yN3V55USPCVix4efb75HxFfA==",
       "dev": true
     },
     "http-proxy": {
@@ -5905,7 +5905,7 @@
         "istanbul-lib-report": "1.1.3",
         "istanbul-lib-source-maps": "1.2.3",
         "istanbul-reports": "1.1.4",
-        "js-yaml": "3.10.0",
+        "js-yaml": "3.11.0",
         "mkdirp": "0.5.1",
         "once": "1.4.0"
       }
@@ -6091,9 +6091,9 @@
       "dev": true
     },
     "js-yaml": {
-      "version": "3.10.0",
-      "resolved": "https://registry.npmjs.org/js-yaml/-/js-yaml-3.10.0.tgz",
-      "integrity": "sha512-O2v52ffjLa9VeM43J4XocZE//WT9N0IiwDa3KSHH7Tu8CtH+1qM8SIZvnsTh6v+4yFy5KUY3BHUVwjpfAWsjIA==",
+      "version": "3.11.0",
+      "resolved": "https://registry.npmjs.org/js-yaml/-/js-yaml-3.11.0.tgz",
+      "integrity": "sha512-saJstZWv7oNeOyBh3+Dx1qWzhW0+e6/8eDzo7p5rDFqxntSztloLtuKu+Ejhtq82jsilwOIZYsCz+lIjthg1Hw==",
       "dev": true,
       "requires": {
         "argparse": "1.0.10",
@@ -6261,9 +6261,9 @@
       }
     },
     "karma-coverage-istanbul-reporter": {
-      "version": "1.4.1",
-      "resolved": "https://registry.npmjs.org/karma-coverage-istanbul-reporter/-/karma-coverage-istanbul-reporter-1.4.1.tgz",
-      "integrity": "sha512-5og0toMjgLvsL9+TzGH4Rk1D0nr7pMIRJBg29xP4mHMKy/1KUJ12UzoqI6mBNCRFa4nDvZS2MRrN7p+RkZNWxQ==",
+      "version": "1.4.2",
+      "resolved": "https://registry.npmjs.org/karma-coverage-istanbul-reporter/-/karma-coverage-istanbul-reporter-1.4.2.tgz",
+      "integrity": "sha512-sQHexslLF+QHzaKfK8+onTYMyvSwv+p5cDayVxhpEELGa3z0QuB+l0IMsicIkkBNMOJKQaqueiRoW7iuo7lsog==",
       "dev": true,
       "requires": {
         "istanbul-api": "1.2.2",
@@ -7546,7 +7546,7 @@
       "integrity": "sha512-9jjUFbTPfEy3R/ad/2oNbKtW9Hgovl5O1FvFWKkKblNXoN/Oou6+9+KKohPK13Yc3/TyunyWhJp6gvRNR/PPAw==",
       "dev": true,
       "requires": {
-        "hosted-git-info": "2.5.0",
+        "hosted-git-info": "2.6.0",
         "is-builtin-module": "1.0.0",
         "semver": "5.5.0",
         "validate-npm-package-license": "3.0.3"
@@ -10659,7 +10659,7 @@
         "commander": "2.14.1",
         "diff": "3.5.0",
         "glob": "7.1.2",
-        "js-yaml": "3.10.0",
+        "js-yaml": "3.11.0",
         "minimatch": "3.0.4",
         "resolve": "1.5.0",
         "semver": "5.5.0",
@@ -11682,7 +11682,7 @@
       "integrity": "sha512-3kOFejWqj5ISpJk4Qj/V7w98h9Vl52wak3CLiw/cDOfbVTq7FeoZ0SdoHHY9PYlHr50ZS42OfvzE2vB4nncKQg==",
       "dev": true,
       "requires": {
-        "acorn": "5.5.0",
+        "acorn": "5.5.1",
         "acorn-dynamic-import": "2.0.2",
         "ajv": "6.2.1",
         "ajv-keywords": "3.1.0",
@@ -12457,7 +12457,7 @@
       "integrity": "sha1-DK+dLXVdk67gSdS90NP+LMoqJOs=",
       "dev": true,
       "requires": {
-        "http-parser-js": "0.4.10",
+        "http-parser-js": "0.4.11",
         "websocket-extensions": "0.1.3"
       }
     },
```

**Comment by jmelberg-okta** [comment] 2018-03-08 06:18
After digging into this a bit - it looks like this issue is being caused by one of Angular's sub-dependencies or Angular itself.

When the tokens are returned via a hash fragment, they're being URL-encoded by Angular (or another lib). When AuthJS attempts to parse this from the URL (see this method in [oauthUtils.js](https://github.com/okta/okta-auth-js/blob/master/lib/oauthUtil.js#L197-L224)) - its unable to correctly convert it into a JSON object.

Therefore, when validating [the state](https://github.com/okta/okta-auth-js/blob/master/lib/token.js#L195-L197) - its is evaluating:

```typescript
if (undefined !== 'someStateValue') {
  throw new AuthSdkError('OAuth flow response state doesn\'t match request state');
}
```

I'll try and dig into this a bit more - but wanted to provide you with a brief description of what is likely the root-cause.

**Comment by Sara3** [comment] 2018-03-13 21:16
I am still getting the same error "ERROR Error: Uncaught (in promise): AuthSdkError: OAuth flow response state doesn't match request state
Error..." Even though that PR is closed

**Comment by jmelberg-okta** [comment] 2018-03-13 21:19
@Sara3 - At this time, we do not support `@angular/router-5.2.8` due to that change. Ensure your `package.json` is set to a prior version.

**Comment by ssaxena48** [comment] 2018-03-14 01:27
I changed the version to point to 5.2.7 but still same issue.

**Comment by mraible** [comment] 2018-03-14 01:33
You changed "@angular/router" to 5.2.7? Did you `rm -rf node_modules` and run `npm install` again? If so, and you still see this issue, are you able to post your project on GitHub so I can try to reproduce the issue?

**Comment by ssaxena48** [comment] 2018-03-14 01:34
Just now I am doing the same step. I missed that one :)

**Comment by ssaxena48** [comment] 2018-03-14 01:54
Like the Okta Cloud, forum also looks like has 24X7 availability and fast response :) .. Thanks for prompt reply .. It works

**Comment by ssaxena48** [comment] 2018-03-14 17:21
Can I use Okta Auth JS with AngularJS 1.5.5 ?

**Comment by mraible** [comment] 2018-03-14 17:35
@ssaxena48 I think so. Have you tried? If you'd like to use our sign-in widget with AngularJS, we have [a sample application](https://github.com/okta/samples-js-angular-1) that shows you how.

Related: [Open Source Framework Samples and Quickstarts for Okta's Developer APIs](https://developer.okta.com/blog/2018/03/06/okta-open-source-samples-and-quickstarts)

**Comment by jmelberg-okta** [comment] 2018-03-14 20:17
Closing this issue as we have identified the root cause.

Angular is set to release a new version to modify the breaking update captured in [this PR](https://github.com/angular/angular/pull/22337).

**Closed by jmelberg-okta** 2018-03-14 20:17 UTC
