### ISSUE TITLE
Question: Can the OktaAuthModule be configured at runtime?

### ISSUE THREAD

**Issue by jakehockey10** [okta/okta-oidc-js#39] opened 2017-11-09 00:05 UTC
Hello,

I've run into an issue where the solution would be to be able to configure the `OktaAuthModule` at runtime, if that even makes sense.

In Angular, we have the two default environments: `dev` (default) and `prod` (`ng build --prod`).  When it comes time to release, and our continuous integration says our tests pass on master, I use Octopus to generate a release by first deploying to our dev staging environment.  If all is well, I deploy to our test staging environment.  After more checks there, I deploy this release to production and all is happy in the world.

The problem is this: each of those staging environments and the production environment have their own domain (i.e. `<app-name>dev.domain.com`, `<app-name>test.domain.com`, and `<app-name>.domain.com`).  This comes into play when I have to configure the `OktaAuthModule` in `app.module.ts`.  When I deploy to my dev staging environment, then try to log in, I get redirected to my production uri instead of my dev one (app.module.ts):

``` typescript
    OktaAuthModule.initAuth({
      issuer: environment.oktaURL,
      redirectUri: `${environment.rootURI}/implicit/callback`,
      clientId: '<client-id>'
    })
```

What we've done to solve this in other places is to have a settings.json file in our bundled application that is accessible through a `AppSettingsService` that makes local http calls to the json file to retrieve configuration settings that Octopus does a Find and Replace on during the deployment process.  But I'm assuming I can't take this same approach here because this is actually happening before I can inject any of my services, correct?

I've thought of some alternatives, but I don't like them: 
- have a separate build for each staging environment in Angular.
  - Octopus provides deploying the same application bundle to several staging environments very easily.  We'd be defeating the purpose of using a deployment system like this if we had to go make another build and have a separate release for each staging environment.  So I don't WANT to do this.
- Have a complicated Find and Replace step in Octopus for looking for the `OktaAuthModule` import statement and replace the redirectUri with the right one.
  - I'm afraid of this one because I don't know what app.module.**js** looks like well enough to to a Find and Replace rule that works 100% of the time.

Any ideas?

**Comment by omgitstom** [comment] 2017-11-10 16:50
Additional discussion:
https://devforum.okta.com/t/can-the-oktaauthmodule-be-configured-at-runtime/723

@jakehockey10 we are going to take a look at this, current best quick fix we currently have is to use separate `NgModules` based on your environment. This is what firebase does.

**Comment by jakehockey10** [comment] 2017-11-10 17:56
@omgitstom That's interesting...Could you elaborate on that?  Do you mean to wrap the OktaAuthModule with another module and have that wrapper module depend on the environment?

**Comment by omgitstom** [comment] 2017-11-10 17:58
@jmelberg-okta mind elaborating the point above?

**Comment by cmckni3** [comment] 2018-02-05 16:28
Is the idea to have a module for each environment? See http://squirrel.pl/blog/2017/07/23/environment-specific-modules-services-and-components-in-angular/

**Comment by cmckni3** [comment] 2018-02-19 20:35
I figured this out a day after my previous comment. I built out a `ConfigService` to load from a JSON file in the assets folder. I use an `APP_INITIALIZER` to load the data and set that a dependency of the `OKTA_CONFIG` factory. Sample code is below.

```
export function initConfig(configService: ConfigService) {
  return () => {
    return configService.loadConfiguration()
      .toPromise();
  };
}

@NgModule({
    ...
    providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: initConfig,
      deps: [ConfigService],
      multi: true
    },
    {
      provide: OKTA_CONFIG,
      useFactory: (configService: ConfigService) => {
        const config = configService.getConfig();
        const oktaConfig = {
          issuer: `${config.okta.baseUrl}/oauth2/${config.okta.authServer}`,
          redirectUri: `${config.okta.redirectUri}/auth/callback`,
          clientId: config.okta.clientId
        };
        return oktaConfig;
      },
      deps: [ConfigService]
    },
  ]
})
export class AppModule { }
```

**Comment by cmckni3** [comment] 2018-04-24 22:07
Works perfectly for me @dpollastrini. AFAIK it changed in ng v5 though.

**Comment by cmckni3** [comment] 2018-04-24 22:13
I'll see if I can get a stackblitz setup with my config service.

**Comment by dpollastrini** [comment] 2018-04-24 22:45
Thanks @cmckni3, Yeah, I've run across some comments indicating that APP_INITIALIZER did exactly what you're describing prior to version ????.  I guess we've upgraded into obsolescence...again.

In any case, our "external configuration" service is "loaded" via APP_INITIALIZER and it works great post bootstrap when injecting into components.... other service provider factories, not so much.

**Comment by cmckni3** [comment] 2018-04-25 00:31
Do you have an example?

**Comment by dpollastrini** [comment] 2018-07-31 16:51
@cmckni3, turns out I am also providing a custom HttpInterceptor that depends on OktaAuthService. Adding a "deps on ConfigurationService" to the HTTP_INTERCEPTORS reference in providers resolved my issue. It wasn't apparent at all where the "undefined config" error was coming from in the original stack trace, so I assumed it was the attempt to provide OKTA_CONFIG, which it was not.  My bad.  Your solution works fine. Thanks!

**Comment by cmckni3** [comment] 2018-08-01 03:45
No problem. Glad you figured it out @dpollastrini!

**Comment by jakehockey10** [comment] 2018-09-27 18:01
@cmckni3 Where does your `ConfigService` live?  We are attempting to take the same approach, and we are providing our service in the same `providers` array in the `NgModule` decorator, and it seems we have a cyclic dependency problem.  Our `useFactory` function gets called over and over and over.

Where do you declare/provide your `ConfigService`?

**Comment by jakehockey10** [comment] 2018-09-27 18:27
Also, I thought what might be different in my scenario is that I have a `TokenInterceptor` to put the access token in the Authorization header for each call out using `HttpClient`, which has my `AuthenticationService` injected into it, which, in turn, has the `OktaAuthService` injected into it.  Playing with the order of providers doesn't seem to make a huge difference, but definitely makes us think there is some sort of circular dependency going on...

**Comment by jakehockey10** [comment] 2018-09-27 19:18
That definitely is the issue.  If I don't use the `TokenInterceptor` this seems to work as one would expect.
However, as you could imagine, having to put the token in the header in any other way requires a lot more code directly proportional to how much I use the `HttpClient` in my services and how many services I have.  Can anyone think of a way to use this approach while also using an `HTTP_INTERCEPTOR`?

**Comment by cmckni3** [comment] 2018-09-27 20:09
I have a `ConfigService` in a core module. It used to be in the application but was moved to a private Angular library. The external library has `AuthTokenInterceptor` in it as well.

You have to be careful about cyclic dependencies with your provider factories. You may have a cyclic dependency where your factory provider has some services injected that depend on `ConfigService` and the factory itself may depend on `ConfigService`.

**Comment by cmckni3** [comment] 2018-09-27 20:11
@jakehockey10 `HTTP_INTERCEPTORS` work fine in my private library which has:

- `ConfigService` - loads `env.json` which contains okta base url, client id, etc
- `AuthTokenInterceptor` adds token to `HttpClient` requests
- `AuthService` wraps logic for calls to `OktaAuthService`

**Comment by jakehockey10** [comment] 2018-09-27 21:06
@cmckni3 , thanks for the response!

I'll try to come up with a way to succinctly show you what my code looks like, but in the meantime, that's pretty similar to my approach.  I'm guessing it is a cyclic dependency, but I don't necessarily get a cyclic dependency error.  I either get a "maximum callstack" error or a `getAccessToken()` is not a function of undefined.  The latter error is coming from the use of my `AuthenticationService` in the `TokenInterceptor`.  The service instance is undefined.  When I remove the `TokenInterceptor`, this is no longer an issue.

I have a separate library for authentication concerns, but I have had trouble moving everything authentication related into that library.  Right now, that library consists of the `AuthenticationService` whose constructor looks like this:
``` typescript
  constructor(private _router: Router, private _okta: OktaAuthService) {
```
The `TokenInterceptor` and `UnauthorizedInterceptor` are both in this library as well:
``` typescript
export class TokenInterceptor implements HttpInterceptor {
  constructor(private _auth: AuthenticationService) {}
```
``` typescript
export class UnauthorizedInterceptor implements HttpInterceptor {
  constructor(private _auth: AuthenticationService) {}
```

My authentication module doesn't list anything in its configuration, but the intent was to configure okta in here.  Right now, the configuration of the okta module is in my core module and looks like this:
``` typescript

@NgModule({
  imports: [
    SharedModule,
    RouterModule,
    HttpClientModule,
    LoggingModule,
  ],
  declarations: [
    OktaCallbackComponent,
    HomeComponent,
    IeHelpComponent,
    ResourcesComponent,
    ProfileComponent,
    SettingsComponent,
    NotFoundComponent,
    ContactComponent,
    InteractiveGuideComponent
  ],
  exports: [InteractiveGuideComponent, IeHelpComponent],
  providers: [
    OktaCallbackComponent,
    AppSettingsService,
    {
      provide: APP_INITIALIZER,
      useFactory: initializeSettings,
      multi: true,
      deps: [AppSettingsService]
    },
    {
      provide: OKTA_CONFIG,
      useFactory: (settingsService: AppSettingsService) => {
        return settingsService.loadConfiguration().then(config => {
          return {
            issuer: `${config.okta.baseUrl}/oauth2/${config.okta.authServer}`,
            redirectUri: `${config.okta.redirectUri}/auth/callback`,
            clientId: config.okta.clientId
          };
        });
      },
      deps: [AppSettingsService]
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: TokenInterceptor,
      multi: true
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: UnauthorizedInterceptor,
      multi: true
    },
    OktaAuthService,
    OktaAuthGuard,
    AuthenticationService,
    IeService,
    MenuService,
    SettingsService,
    DevExtremeThemeService,
    AdminGuard
  ]
})
export class CoreModule {}

export function initializeSettings(settingsService: AppSettingsService) {
  return () => settingsService.loadConfiguration();
}

```
I get different errors depending on whether I list the `AuthenticationService` in the `deps` property of the `HTTP_INTERCEPTORS` provider listings.  For example:
``` typescript
    {
      provide: HTTP_INTERCEPTORS,
      useClass: TokenInterceptor,
      multi: true,
      deps: [AuthenticationService]
    }
```
That seems to be something that is needed, it doesn't solve this issue outright.

My `AppSettingsService` looks like this:
``` typescript

@Injectable()
export class AppSettingsService {
  private _settings: AppSettings;

  tableau: TableauApi;
  portalApi: PortalApi;
  google: GoogleApi;
  bing: BingMapsApi;
  version: string;
  okta: Okta;

  constructor(private http: HttpClient) { }

  loadConfiguration() {
    return this.http
      .get('assets/settings.json')
      .pipe(
        map(res => {
          this._settings = res as AppSettings;
          this.tableau = this._settings.tableau;
          this.portalApi = this._settings.portalApi;
          this.google = this._settings.google;
          this.bing = this._settings.bing;
          this.version = this._settings.version;
          this.okta = this._settings.okta;
          return this._settings;
        }))
      .toPromise();
  }

  public getSettings(): AppSettings {
    return this._settings;
  }

  public get isLoaded(): boolean {
    return this._settings != null;
  }
}

```

Without sharing the codebase, is there anything else I can share with you on here that would help clarify my situation?

**Comment by jakehockey10** [comment] 2018-09-27 22:37
The external library issue was fixed by extracting the function I was passing into `useFactory` for the `OKTA_CONFIG` to an exported function as well.  I had to make sure that any lambdas in both exported functions were assigned to a variable first.

**Comment by cmckni3** [comment] 2018-09-27 22:59
I was about to comment about that. Yes functions for `useFactory` must be exported because of how they are referenced by Angular.

**Comment by jakehockey10** [comment] 2018-09-28 02:32
@cmckni3 in your app where you have this working in an angular library project, is that something you'd be willing to share in some capacity? I'd like my authentication/authorization concerns to be encapsulated in this separate library of mine to use on multiple applications in my workspace

**Comment by cmckni3** [comment] 2018-09-28 17:17
Yep, that's the reason I created the library. Had to spin up 4 apps this year and wanted a library to use in all of them.

I am willing to consult. Email me at the address [here](https://github.com/cmckni3/docker-alpine-build-tools/blob/master/Dockerfile#L2).

**Comment by jakehockey10** [comment] 2018-10-07 07:51
Man, I can't believe I'm still stuck on this.  The `APP_INITIALIZER` does not resolve before I spiral into the OKTA_CONFIG provider and the config service is not initialized with the information it needs to initialize Okta.  Apparently Angular waits for `APP_INITIALIZER` providers who are lambdas with return type promises, but I don't see anything like that in the Okta module.  

I don't understand why, despite the documentation and community saying it will, the `APP_INITIALIZER` just won't resolve before moving on down the line of providers.

**Comment by cmckni3** [comment] 2018-10-08 16:55
That hasn't been my experience for Angular >= 5.0.0. The `APP_INITIALIZER` fires first.

I just noticed that your `AppSettingsService` is first in the list of providers. The order shouldn't matter on `providers` imo but it does.

In my apps/library: `APP_INITIALIZER` is the first provider and `OKTA_CONFIG` is the second provider. The `APP_INITIALIZER` factory runs, returns the result of the promise (I am calling `.toPromise()` in the factory function but that doesn't matter), then the `OKTA_CONFIG` factory runs.

I noticed also you called your module `CoreModule`. That leads me to believe it may be imported in multiple modules or the issue you are having is with a lazy loaded module receiving a different instance of the `OKTA_CONFIG` factory return value. In my library, there's a `CoreModule` that uses [`forRoot`](https://angular.io/guide/singleton-services#forroot) to specify the `APP_INITIALIZER` and `OKTA_CONFIG` providers which is imported in the `AppModule` only (`CoreModule.forRoot()`)

**Comment by OlgaDan25** [comment] 2018-11-02 22:01
@cmckni3 Chris, I use okta-angular librarym and followed the steps provided above:
1) built out a ConfigService to load from a JSON file in the assets folder; 
2) used an APP_INITIALIZER to load the data and set that a dependency of the OKTA_CONFIG factory. 
But the issue is with AuthorizationInterceptor 
{provide: HTTP_INTERCEPTORS, useClass: AuthorizationInterceptor, deps: [ConfigService], multi: true}, The error I get is 
![image](https://user-images.githubusercontent.com/44713538/47942377-157ae080-dec8-11e8-9597-feece800357d.png)

What do you think ? What am I doing wrong?

_here is some of my ngModule in AppComponent_
![image](https://user-images.githubusercontent.com/44713538/47942548-bcf81300-dec8-11e8-96d2-edd9cf39fcfc.png)

_here is my interceptor_
![image](https://user-images.githubusercontent.com/44713538/47942654-09435300-dec9-11e8-85f7-15242dac1c3f.png)

**Comment by OlgaDan25** [comment] 2018-11-06 20:06
@cmckni3 Thank you for your answer, Chris! 
If I use OktaAuthService dependency for AuthorizationInterceptor, then I have an error 
![image](https://user-images.githubusercontent.com/44713538/48090234-5c244f80-e1d4-11e8-8045-9f1c54aa108b.png)

I import  { OKTA_CONFIG, OktaAuthGuard, OktaCallbackComponent, OktaAuthModule, **OktaAuthService** } from '@okta/okta-angular'.  Should I better create AuthService which wraps logic for calls to OktaAuthService? What do you think?
If yes, please send me any link where I can learn how to do it. Thank you so much for your help!

**Comment by cmckni3** [comment] 2018-11-06 20:36
@OlgaDan25 that means the `OktaAuthService` is missing the configuration. I use this in my providers for configure dynamically.

```
    {
      provide: OKTA_CONFIG,
      useFactory: (configService: ConfigService) => {
        const config = configService.getConfig();
        const oktaConfig = {
          issuer: `${config.okta.baseUrl}/oauth2/${config.okta.authServer}`,
          redirectUri: `${config.okta.redirectUri}/auth/callback`,
          clientId: config.okta.clientId
        };
        return oktaConfig;
      },
      deps: [ConfigService]
    },
```

You could hardcode these values like so if you don't need multiple environments.

```
export function oktaConfigFactory() {
  return {
    issuer: `https://{ID}.oktapreview.com/oauth2/default`,
    redirectUri: 'http://localhost:4200/auth/callback',
    clientId: '{{CLIENT_ID_HERE}}'
  };
}

providers: [
    ...
    {
      provide: OKTA_CONFIG,
      useFactory: oktaConfigFactory,
    },
]
```

**Comment by OlgaDan25** [comment] 2018-11-06 22:01
@cmckni3 Thanks, Chris! When the values are hardcoded and OktaAuthModule.initAuth( ) is used - everything works perfectly, but I need multiple environments. 
I will work with ConfigService more. Thanks for pointing that out.
Will get back with results tomorrow ;)

**Comment by swiftone** [comment] 2020-01-31 21:51
Closing this issue as it appears the injection pattern has been resolved and angular version churn has ceased to impact this.

If anyone has a related problem feel free to open a new issue with details and reference this one.

**Closed by swiftone** 2020-01-31 21:51 UTC
Labels: angular
