### ISSUE TITLE
okta-angular times out in tokenmanager.js

### ISSUE THREAD

**Issue by Sara3** [okta/okta-oidc-js#435] opened 2019-04-24 17:22 UTC
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
<Detailed Description: Angular registers a global window.getAngularTestability(element), which returns a PublicTestability object. This object has a method whenStable(callback), which is what Protractor’s waitForAngular() uses.  Protractor will wait until the Angular Zone stabilizes, this means long running async operations will block tests from continuing. 

Inside the okta-auth-js library the TokenManager.js script keeps track of tokens and their expiration time. When the expiration time of the token is up the task in the settimeout block is invoked, all the while the Protractor test framework is waiting for that timeout to ivoke, thus blocking our test runs. The proposed work around from protractor is to run such timeouts outside the angular zone via this.ngZone.runOutsideAngular() however this is no possible due to when the TokenManager is initialized. TokenManager is initialized during construction of OktaAuthService which is creating during initialization of our app module. We tried using a factory function that creates the OktaAuthService outside the angular zone, but this didn't actually work.

## Expected behavior
Does not keep a timer internally

## Minimal reproduction of the problem with instructions
.\node_modules\@okta\okta-auth-js\lib\TokenManager.js

Line 56:

  var expireEventTimeout =  setTimeout(function() { emitExpired(tokenMgmtRef, key, token); }, expireEventWait);

 

Line 56 schedules a task within the angular zone to run after the auth and id tokens expire, for our app this is 4 hours, this means this task stays scheduled until the 4 hours is up thus making the angular zone unstable for up to 4 hours. TokenManager is an internal storage utility to the OKTA angular library for management of tokens.

 

Exact reproduction steps are very involved. It might be better to schedule a call to show the issue, however here is a general idea on how to reproduce:

 

Install node.js
Create an angular2+ app (we used angular 6)
Create an app within OKTA portal
Bootstrap your angular app using the quick start okta guide for client side setup : https://developer.okta.com/quickstart/#/angular/nodejs/express#client_setup
Configure protractor https://www.protractortest.org/#/tutorial
Configure your protractor e2e tests to use the native async/await in your tests https://www.protractortest.org/#/async-await
!important: ensure your protractor config disables the selenium promise manager: SELENIUM_PROMISE_MANAGER: false
Write a test that includes workaround script for logging into a non-angular page (see attached)
Update test with async operation
Run test. Note test fail due to timeout error ScriptTimeoutError: script timeout: result was not received in xxx seconds

## Environment

zone.js: 0.8.26
@okta/okta-angular: 1.2.0
protractor: 5.4.0
selenium-webdriver: 4.0.0-alpha.1
Chrome: 73
 Steps to Reproduce: Writing an async test like the following will never resolve due to tests being blocked:
await element(by.id('SearchButton')).click()

**Comment by wendrickje** [comment] 2019-04-24 18:33
login script mentioned above is as follows
```javascript
    /*
    * @param email Email to be logged in with
    * @param password Password to be logged in with
    * @param url URL route we are trying to access
    * @returns None
    */
async login(email, password, url) {
    await browser.waitForAngularEnabled(false);   // Need to turn off waiting for angular when going to normal page because
    // redirect will make the following get insta-fail waiting for Angular
    await browser.get('/' + url);

    const until = protractor.ExpectedConditions;
       
    await browser.driver.wait(until.visibilityOf(element(by.name('username'))));
    browser.driver.findElement(by.name('username')).sendKeys(email);
    browser.driver.findElement(by.className('button button-primary')).click();
    await browser.driver.wait(until.visibilityOf(element(by.name('username'))));
    await browser.driver.wait(until.visibilityOf(element(by.name('password'))));
    browser.driver.findElement(by.name('password')).sendKeys(password);
    browser.driver.findElement(by.className('button button-primary')).click();
    await browser.wait(until.urlContains('localhost'));

    await browser.waitForAngularEnabled(true); // Turn waiting for angular back on
}
```

**Comment by jraadt** [comment] 2019-04-26 19:58
Is this related to https://github.com/okta/okta-oidc-js/issues/423 ?

**Comment by wendrickje** [comment] 2019-04-26 22:03
@jraadt similar but not the same.

**Comment by mderoche** [comment] 2019-07-12 18:25
I'm confused here, does anyone actually use this library with Protractor successfully, without having to permanently disable `waitForAngularEnabled`?

**Comment by korsakov** [comment] 2019-12-14 01:33
We encountered a related issue integrating Okta with an Angular app, and found that running auth client _outside_ of NgZone allows protractor to execute tests. Depending on your use case, this may be the recommendable option.

**Comment by swiftone** [comment] 2019-12-16 22:02
Okta isn't looking to make recommendations on how to test your apps in general.  For this specific case the issue is that the polling loop exists OUTSIDE the angular code.   (This is why @korsakov is finding success by running the auth code outside of NGZone).  You should be able to set autoRenew: false to prevent the issue (I've not confirmed that).

Recommendations beyond that are outside the scope of the SDKs, but we are happy to see users share suggestions and experiences with each other.

**Comment by wendrickje** [comment] 2019-12-17 01:06
> Okta isn't looking to make recommendations on how to test your apps in general. For this specific case the issue is that the polling loop exists OUTSIDE the angular code. (This is why @korsakov is finding success by running the auth code outside of NGZone). You should be able to set autoRenew: false to prevent the issue (I've not confirmed that).
> 
> Recommendations beyond that are outside the scope of the SDKs, but we are happy to see users share suggestions and experiences with each other.

If setting autoRenew to false works I'm happy to close the issue. I'm not sure I ever tried that myself.

**Comment by swiftone** [comment] 2020-01-06 21:47
Closing.  If this continues to be an issue please feel free to reopen with more details.

**Closed by swiftone** 2020-01-06 21:47 UTC
Labels: bug, priority-pending, requires-reproduce
