### ISSUE TITLE
SecureRoute issue 3.0.5+ makes all routes require auth

### ISSUE THREAD

**Issue by fetters5** [okta/okta-oidc-js#888] opened 2020-09-01 17:54 UTC
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
Regardless of route the user is always redirected to login (was not happening before 3.0.5)
`

      <Switch>
        <Route path="/authorization-code/callback" component={LoginCallback} />
          <Route exact path="/" component={LandingPage}></Route>
          <Route path="/anonymous" component={TestComponent}></Route>
          <SecureRoute exact path="/protected" component={TestComponent}></SecureRoute>
      </Switch>
`

## Expected behavior

I would expect that only the secure route would redirect to the auth screen 

## Environment

- Package Version: @okta/okta-react 3.0.5
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by shuowu** [comment] 2020-09-01 20:42
@fetters5 I cannot reproduce the issue locally with [okta-react-sample](https://github.com/okta/samples-js-react)

If you can reach out to our support team at developers@okta.com you can share details of your configuration and they can help us find out what is happening.

**Comment by fetters5** [comment] 2020-09-01 21:57
@shuowu I used the sample you linked and as soon as I update @okta/okta-react to 3.05 or 3.06 it redirects to the login page on app start if I am not authenticated. Works as intended in 3.0.4 but this particular app needs the new features introduced in 3.0.5

**Comment by shuowu** [comment] 2020-09-01 23:35
I am still not able to repro the issue. Also, it's expected to be redirect back to login if the app start from a protected route.

**Comment by fetters5** [comment] 2020-09-02 00:13
Ok, I was using the code from  https://github.com/okta/samples-js-react/tree/master/okta-hosted-login.
The only changes I made to that repo is to bump the version and target my dev okta instance

I will send an email to the address above.  Thank you.

**Comment by TheFuzzard** [comment] 2020-09-08 16:26
@shuowu just did a quick test with the root path, which is under the _Home_ component and with 3.0.6 it no longer displays the page without being authenticated, which was not happening on previous versions

**Comment by shuowu** [comment] 2020-09-08 16:37
@TheFuzzard @fetters5 It looks like I was misconfigured my local env somehow, I can repro the issue now.

Internal Ref: OKTA-328349

**Comment by shuowu** [comment] 2020-09-08 17:33
The issue is without wrapping routes inside a `<Switch>` component, React will try to render all SecureRoutes, then trigger the `useEffect` callback to login the user.

A workaround would be to always wrap routes inside a `<Switch>` component.

**Comment by fetters5** [comment] 2020-09-08 19:02
Hmm,  that does not seems to be the case for me.  On my project they are wrapped in a switch comp.

**Comment by shuowu** [comment] 2020-09-08 19:32
@fetters5 Can you share the structure of your routes? I suspect you put `<SecureRoute>` at the top, move them to the bottom of the `<Switch>` block may fix the issue.

**Comment by fetters5** [comment] 2020-09-09 15:13
I used the example at the top of the page, doesn't work regardless of switch or not for me.

**Comment by aarongranick-okta** [comment] 2020-09-09 20:54
@fetters5 Thanks for reporting this! I was able to reproduce this issue locally using the hosted login sample. We will start working on a fix and/or workaround.

**Comment by fetters5** [comment] 2020-09-10 02:08
Glad to hear you all can reproduce.  Thank you for the quick responses

**Comment by aarongranick-okta** [comment] 2020-09-10 22:38
@fetters5 We have pushed a new version `@okta/okta-react@3.0.7` It **should** fix the issue you are seeing.

**Comment by fetters5** [comment] 2020-09-11 16:08
Did a quick test and it seems to have fixed my issues, now only those routes that use <SecureRoute/> force authentication, thanks!

**Comment by swiftone** [comment] 2020-09-18 18:41
Closing as okta-react 3.0.7 appears to have resolved the issue

**Closed by swiftone** 2020-09-18 18:41 UTC
Labels: bug, priority-high, react
